### ISSUE TITLE
front-end-cal does not work because of bug

### ISSUE THREAD

**Issue by OrbitTheSun** [gnss-sdr/gnss-sdr#102]
In the `next` branch there is a bug in front-end-cal that prevents satellites from being found. 

By commenting out a line in `gps_l1_ca_pcps_acquisition_fine_doppler.cc`
the PRN code is no longer loaded. The acquisition then fails naturally.

    void GpsL1CaPcpsAcquisitionFineDoppler::init()
    {
        acquisition_cc_->init();
        //set_local_code();
    }

After I commented in `set_local_code()` it works again as expected.

**Comment by carlesfernandez** [comment]
Thank you. Fixed in the 'next' branch at 1e6f053c37923bc5ac8e49809b7496f8a07fb15a
