### ISSUE TITLE
[  FAILED  ] MatioTest.WriteAndReadGrComplex

### ISSUE THREAD

**Issue by baguzajja** [gnss-sdr/gnss-sdr#115]
Dear Dev

i have some problem with my gnss-sdr
when i try to run ./run_tests

have some failed test

[  FAILED  ] 2 tests, listed below:
[  FAILED  ] MatioTest.WriteAndReadDoubles
[  FAILED  ] MatioTest.WriteAndReadGrComplex

Any body help me ??

**Comment by carlesfernandez** [comment]
Please do `sudo apt-get install libmatio-dev` and build GNSS-SDR again (`cmake .. && make`).

It seems that the Matio library was build automatically but the hdf5 library was not found, so it can't read or write .mat compressed files. The package `libmatio-dev` will install both.

**Comment by baguzajja** [comment]
thanks ... worked
