### ISSUE TITLE
My first position fix

### ISSUE THREAD

**Issue by kasmf** [gnss-sdr/gnss-sdr#120]
what is My first position fix?

**Comment by carlesfernandez** [comment]
It is a [page](http://gnss-sdr.org/my-first-fix/) describing the first steps using GNSS-SDR.

**Comment by kasmf** [comment]
how to correct the error, when the command in a terminal is like $ gnss-sdr --config_file=./my-first-GNSS-SDR-receiver.conf the error it comes like bellow:
linux; GNU C++ version 5.3.1 20151219; Boost_105800; UHD_003.009.002-0-unknown

Initializing GNSS-SDR v0.0.6.git-- ... Please wait.
Logging will be done at "/tmp"
Use gnss-sdr --log_dir=/path/to/log to change that.
Processing file /home/kas/GNSS-raw-signal/2013_04_04_GNSS_SIGNAL_at_CTTC_SPAIN/2013_04_04_GNSS_SIGNAL_at_CTTC_SPAIN.dat, which contains 1600000000 [bytes]
GNSS signal recorded time to be processed: 99.999 [s]
Using Volk machine: avx2_64_mmx_orc
E0206 09:15:36.066758  3136 gnss_flowgraph.cc:355] itemsize mismatch: gps_l1_ca_pvt_cc0:0 using 8, null_sink0:0 using 2
E0206 09:15:36.066821  3136 control_thread.cc:139] Unable to connect flowgraph
Total GNSS-SDR run time 0.001682 [seconds]
GNSS-SDR program ended.
gnss-sdr: /usr/include/boost/thread/pthread/condition_variable_fwd.hpp:81: boost::condition_variable::~condition_variable(): Assertion `!ret' failed.
Aborted (core dumped)

**Comment by carlesfernandez** [comment]
You are using an old version of GNSS-SDR (v0.0.6 according to your log). The latest stable release is 0.0.9, and the `next` branch of the repository contains a number of bug fixes and the addition of new features.

Please build the software from source, as explained [here](http://gnss-sdr.org/build-and-install/).

**Comment by kasmf** [comment]
i remove the gnss-sdr using $ sudo apt-get remove gnss-sdr and install using $ sudo apt-get install gnss-sdr to get the latest gnss-sdr version (gnss-sdr version 0.0.9). still the gnss-sdr version is gnss-sdr version 0.0.6,... how to remove the old gnss-sdr version and install the latest version (gnss-sdr version 0.0.9)?

**Comment by carlesfernandez** [comment]
Please do this:

 * Remove the package:
```
$ sudo apt-get remove gnss-sdr
```

* Add dependencies not required in previous versions:
```
$ sudo apt-get install libhdf5-dev libmatio-dev
```
 * Build GNSS-SDR from source:

```
$ git clone https://github.com/gnss-sdr/gnss-sdr.git
$ cd gnss-sdr/build
$ git checkout next
$ cmake ..
$ make -j4
$ sudo make install
```

**Comment by acebrianjuan** [comment]
Hi @kasmf 

The version of GNSS-SDR that is available in the Ubuntu repositories was frozen at v0.0.6, which is **not** the latest version. Therefore, installing GNSS-SDR using  `sudo apt install gnss-sdr` will **not** upgrade you to the latest version (v0.0.9), because it is not available yet to the package manager.

You can check which version of a package is available to the package manager with the command: 

    $ apt policy <package>

In the case of GNSS-SDR, you will see something like this:
```
$ apt policy gnss-sdr 
gnss-sdr:
  Installed: (none)
  Candidate: 0.0.6-1
  Version table:
     0.0.6-1 500
        500 http://es.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
```
Suggested read: [Why don't the Ubuntu repositories have the latest versions of software?](https://askubuntu.com/q/151283)

If you want the latest version you will have to build GNSS-SDR from source following [the instructions](https://github.com/gnss-sdr/gnss-sdr/issues/120#issuecomment-363437732) provided by @carlesfernandez 

On a side note, you are welcome to ask questions like this one in the GNSS-SDR [mailing list](https://lists.sourceforge.net/lists/listinfo/gnss-sdr-developers).

**Comment by kasmf** [comment]
i follow the instructions provided  by @carlesfernandez, but  it comes the error on the terminal as:
kas@kas-HP-ProDesk-490-G3-MT-Business-PC:~/gnss-sdr/build$ make -j4
make: *** No targets specified and no makefile found.  Stop.
how to correct please?

**Comment by carlesfernandez** [comment]
Did you get any error in the configuration step (that is, `cmake ..`)?

If cmake complained, could you post here the message?

**Comment by kasmf** [comment]
no error in the configuration step of   cmake .., but the error is in the configuration step of make -j4

**Comment by kasmf** [comment]
sorry the error is in the configuration step of cmake ..              as:
kas@kas-HP-ProDesk-490-G3-MT-Business-PC:~/gnss-sdr/build$ cmake ..
-- Configuring GNSS-SDR v0.0.9.git-next-413ab8c to be built on Ubuntu GNU/Linux Release 16.04 (64 bits)
-- Build type not specified: defaulting to Release.
-- Checking for ARM
-- System is not ARM
-- Testing for SIMD extensions
--  Googletest has not been found.
--  Googletest will be downloaded and built automatically 
--  when doing 'make'. 
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   date_time
--   system
--   filesystem
--   thread
--   serialization
--   chrono
--   unit_test_framework
--   program_options
--   atomic
-- Checking for GNU Radio Module: RUNTIME
-- Checking for module 'gnuradio-runtime'
--   No package 'gnuradio-runtime' found
--  * INCLUDES=GNURADIO_RUNTIME_INCLUDE_DIRS-NOTFOUND
--  * LIBS=GNURADIO_RUNTIME_LIBRARIES_gnuradio-runtime-NOTFOUND
-- Could NOT find GNURADIO_RUNTIME (missing:  GNURADIO_RUNTIME_LIBRARIES GNURADIO_RUNTIME_INCLUDE_DIRS) 
-- GNURADIO_RUNTIME_FOUND = FALSE
-- Required GNU Radio Component: RUNTIME missing!
-- Checking for GNU Radio Module: ANALOG
-- Checking for module 'gnuradio-analog'
--   No package 'gnuradio-analog' found
--  * INCLUDES=GNURADIO_ANALOG_INCLUDE_DIRS-NOTFOUND
--  * LIBS=GNURADIO_ANALOG_LIBRARIES_gnuradio-analog-NOTFOUND
-- Could NOT find GNURADIO_ANALOG (missing:  GNURADIO_ANALOG_LIBRARIES GNURADIO_ANALOG_INCLUDE_DIRS) 
-- GNURADIO_ANALOG_FOUND = FALSE
-- Required GNU Radio Component: ANALOG missing!
-- Checking for GNU Radio Module: BLOCKS
-- Checking for module 'gnuradio-blocks'
--   No package 'gnuradio-blocks' found
--  * INCLUDES=GNURADIO_BLOCKS_INCLUDE_DIRS-NOTFOUND
--  * LIBS=GNURADIO_BLOCKS_LIBRARIES_gnuradio-blocks-NOTFOUND
-- Could NOT find GNURADIO_BLOCKS (missing:  GNURADIO_BLOCKS_LIBRARIES GNURADIO_BLOCKS_INCLUDE_DIRS) 
-- GNURADIO_BLOCKS_FOUND = FALSE
-- Required GNU Radio Component: BLOCKS missing!
-- Checking for GNU Radio Module: FFT
-- Checking for module 'gnuradio-fft'
--   No package 'gnuradio-fft' found
--  * INCLUDES=GNURADIO_FFT_INCLUDE_DIRS-NOTFOUND
--  * LIBS=GNURADIO_FFT_LIBRARIES_gnuradio-fft-NOTFOUND
-- Could NOT find GNURADIO_FFT (missing:  GNURADIO_FFT_LIBRARIES GNURADIO_FFT_INCLUDE_DIRS) 
-- GNURADIO_FFT_FOUND = FALSE
-- Required GNU Radio Component: FFT missing!
-- Checking for GNU Radio Module: FILTER
-- Checking for module 'gnuradio-filter'
--   No package 'gnuradio-filter' found
--  * INCLUDES=GNURADIO_FILTER_INCLUDE_DIRS-NOTFOUND
--  * LIBS=GNURADIO_FILTER_LIBRARIES_gnuradio-filter-NOTFOUND
-- Could NOT find GNURADIO_FILTER (missing:  GNURADIO_FILTER_LIBRARIES GNURADIO_FILTER_INCLUDE_DIRS) 
-- GNURADIO_FILTER_FOUND = FALSE
-- Required GNU Radio Component: FILTER missing!
-- Checking for GNU Radio Module: PMT
-- Checking for module 'gnuradio-runtime'
--   No package 'gnuradio-runtime' found
--  * INCLUDES=GNURADIO_PMT_INCLUDE_DIRS-NOTFOUND
--  * LIBS=GNURADIO_PMT_LIBRARIES_gnuradio-pmt-NOTFOUND
-- Could NOT find GNURADIO_PMT (missing:  GNURADIO_PMT_LIBRARIES GNURADIO_PMT_INCLUDE_DIRS) 
-- GNURADIO_PMT_FOUND = FALSE
-- Required GNU Radio Component: PMT missing!
-- CMake cannot find GNU Radio >= 3.7.3
Go to https://github.com/gnuradio/pybombs
and follow the instructions to install GNU Radio in your system.
CMake Error at CMakeLists.txt:505 (message):
  GNU Radio 3.7.3 or later is required to build gnss-sdr


-- Configuring incomplete, errors occurred!
See also "/home/kas/gnss-sdr/build/CMakeFiles/CMakeOutput.log".
See also "/home/kas/gnss-sdr/build/CMakeFiles/CMakeError.log".

**Comment by acebrianjuan** [comment]
As far as I know, that error message indicates that some dependencies are missing ([source](https://askubuntu.com/q/103348)).

Did you install all [the dependencies](url) that are required by GNSS-SDR?

Try following these steps:

1. Install all the dependencies:

```
$ sudo apt-get install build-essential cmake git libboost-dev \
   libboost-date-time-dev libboost-system-dev libboost-filesystem-dev \
   libboost-thread-dev libboost-chrono-dev libboost-serialization-dev \
   libboost-program-options-dev libboost-test-dev liblog4cpp5-dev \
   libuhd-dev gnuradio-dev gr-osmosdr libblas-dev liblapack-dev \
   libarmadillo-dev libgflags-dev libgoogle-glog-dev libhdf5-dev \
   libgnutls-openssl-dev libmatio-dev python-mako python-six \
   googletest
```

2. Run `$ ./configure` inside the` gnss-sdr/build` directory

3. Then continue with the installation

```
$ make -j4
$ sudo make install
```

**Comment by acebrianjuan** [comment]
I have updated the instructions on my previous comment. The `$ ./configure` script had nothing to do in this scenario.

**Comment by carlesfernandez** [comment]
The important info from the CMake message is:

```
-- CMake cannot find GNU Radio >= 3.7.3
Go to https://github.com/gnuradio/pybombs
and follow the instructions to install GNU Radio in your system.
CMake Error at CMakeLists.txt:505 (message):
GNU Radio 3.7.3 or later is required to build gnss-sdr
```

You need to install a version of GNU Radio equal or greater than 3.7.3

According to https://packages.ubuntu.com/search?keywords=gnuradio, the package that comes with Ubuntu 16.04 is version 3.7.9, so you can use the package for installing it. Please follow the steps described by @acebrianjuan

**Comment by kasmf** [comment]
i follow the instruction of acebrianjuan, but it comes the error as:
E: Unable to locate package googletest
how to set the error please?

**Comment by acebrianjuan** [comment]
This error means that the package manager is unable to find a package called `googletest` in the official repositories. Never mind, if you pay attention to the [cmake log](https://github.com/gnss-sdr/gnss-sdr/issues/120#issuecomment-363752949) that you posted previously, `make` will take care of that:

```
-- Googletest has not been found.
-- Googletest will be downloaded and built automatically
-- when doing 'make'.
```

So proceed with the building process ([step #2](https://github.com/gnss-sdr/gnss-sdr/issues/120#issuecomment-363753613)) and let us know about your progress.

**Comment by carlesfernandez** [comment]
The package `googletest` was named `libgtest-dev` in Ubuntu 16.04. Anyway, CMake will automatically download the source code and build it for you if it does not find that package in your system. So please proceed with doing `make` and let us know.

**Comment by kasmf** [comment]
thank you very much for all of you help me ...  i follow the acebrianjuan instructions, it is work fine.

**Comment by vasu471** [comment]
2013_04_04_GNSS_SIGNAL_at_CTTC_SPAIN.dat
can some body provide the IF intermediate frequency and Sampling frequency for the above data

**Comment by acebrianjuan** [comment]
Hi @vasu471 

According to the information available in the [GNSS-SDR website](http://gnss-sdr.org/my-first-fix/#step-2-download-a-file-of-raw-signal-samples), the file `2013_04_04_GNSS_SIGNAL_at_CTTC_SPAIN.dat`

> contains 100 seconds of raw GNSS signal samples collected by a RF front-end centered at 1,575.42 MHz, that was delivering baseband samples at 4 MS/s, in an interleaved I&Q 16-bit integer format.

**Comment by kasmf** [comment]
thank you very much for all of you help me ...  i follow the acebrianjuan instructions, it is work fine.

**Comment by kasmf** [comment]
is it possible position fix with gnss-sdr by receiving the real time of gps signal ? that means by configuring 
the rf front end instead of the downloaded a file of raw signal samples. if possible, how we follow the instructions  ?

**Comment by acebrianjuan** [comment]
Glad to help you @kasmf 

The installation instructions were taken from [gnss-sdr.org](http://gnss-sdr.org/), so credit should go [its contributors](https://github.com/gnss-sdr/geniuss-place/graphs/contributors). All the inner workings of GNSS-SDR are documented there!

> is it possible position fix with gnss-sdr by receiving the real time of gps signal ?

Yes!

> if possible, how we follow the instructions ?

A very popular and inexpensive front-end to get started with is the RTL2832U. You will need an active antenna too. Instructions can be found at: [GNSS-SDR operation with a Realtek RTL2832U USB dongle DVB-T receiver](http://gnss-sdr.org/docs/tutorials/gnss-sdr-operation-realtek-rtl2832u-usb-dongle-dvb-t-receiver/)

**Comment by kasmf** [comment]
thank you acebrianjuan !

**Comment by ssciancalepore** [comment]
Dear all,

I have just installed the last version of the gnss-sdr package using pybombs, and the version is gnss-sdr version _0.0.9.git-next-6dd47336._

I also downloaded the real traces of the 2013_04_04_GNSS_SIGNAL_at_CTTC_SPAIN.dat experiment, and ran the gnss-sdr tool with the command:

`gnss-sdr --config-file=./conf/gnss-sdr.conf --log_dir=./logs/`

Note that, in the config file, I have just modified the path of the source file to indicate the path of the local copy of the ".dat" file.

However, the tool does not generate any kml output, but only a log file with many messages, showing acquisition and immediate loss of lock to the satellites.

I have tried different combinations of the `GNSS-SDR.internal_fs_sps` and the `SignalSource.sampling_frequency parameters` (Default: both 4000000), but nothing changes.

Has anyone already solved this issue?

Thanks a lot for your suggestions

**Comment by carlesfernandez** [comment]
Please update your repo and feel free to reopen the issue if you still find problems.

**Comment by wamlord** [comment]
> Please do this:
> 
> * Remove the package:
> 
> ```
> $ sudo apt-get remove gnss-sdr
> ```
> 
> * Add dependencies not required in previous versions:
> 
> ```
> $ sudo apt-get install libhdf5-dev libmatio-dev
> ```
> 
> * Build GNSS-SDR from source:
> 
> ```
> $ git clone https://github.com/gnss-sdr/gnss-sdr.git
> $ cd gnss-sdr/build
> $ git checkout next
> $ cmake ..
> $ make -j4
> $ sudo make install
"

When I get "make -j4" i get
make: *** No targets specified and no makefile found.  Stop.
whats's the deal?

**Comment by acebrianjuan** [comment]
Hi @wamlord,

This same error was addressed in this issue.
Please read from [this comment](https://github.com/gnss-sdr/gnss-sdr/issues/120#issuecomment-363707768) onwards.

Hopefully this will be enough to solve your problem.

Regards,
Álvaro

**Comment by wamlord** [comment]
> Hi @wamlord,
> 
> This same error was addressed in this issue.
> Please read from [this comment](https://github.com/gnss-sdr/gnss-sdr/issues/120#issuecomment-363707768) onwards.
> 
> Hopefully this will be enough to solve your problem.
> 
> Regards,
> Álvaro

![ca](https://user-images.githubusercontent.com/61922722/76173490-905fa580-6165-11ea-8817-a3fcae09bb06.png)
ok now what?

**Comment by pyjhky1315** [comment]
> It is a [page](http://gnss-sdr.org/my-first-fix/) describing the first steps using GNSS-SDR.

I'm sorry to bother you, could you help me understand why this is happening？

eugene@ubuntu:~/gnss-sdr/conf$ sudo gnss-sdr --config_file=./hackrf.conf
linux; GNU C++ version 7.3.0; Boost_106501; UHD_003.010.003.000-0-unknown

Initializing GNSS-SDR v0.0.19.git-main-87fcfd237 ... Please wait.
Logging will be written at "/tmp"
Use gnss-sdr --log_dir=/path/to/log to change that.
OsmoSdr arguments: hackrf,bias=1
gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.11
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp
Using HackRF One with firmware local-79baef7
Enabled antenna bias voltage
Actual RX Rate: 2e+06 [SPS]...
Actual RX Freq: 1.57542e+09 [Hz]...
PLL Frequency tune error: 0 [Hz]...
Actual RX Gain: 14 dB...
Actual Bandwidth: 6e+06 [Hz]...
RF Channels: 1
Starting a TCP/IP server of RTCM messages on port 2101
The TCP/IP server of RTCM messages is up and running. Accepting connections ...
E0919 05:52:24.634222 118200 gnss_flowgraph.cc:1140] Can't connect signal conditioner 1 to channel 10: vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
Unable to connect flowgraph
Stopping TCP/IP server on port 2101
Total GNSS-SDR run time: 0.528808 [seconds]
GNSS-SDR program ended.
eugene@ubuntu:~/gnss-sdr/conf$

and it is  the conf

[GNSS-SDR]

;######### GLOBAL OPTIONS ##################
GNSS-SDR.internal_fs_sps=8000000
GNSS-SDR.Beidou_banned_prns=56,57,58

SignalSource.implementation=Osmosdr_Signal_Source
SignalSource.item_type=gr_complex
SignalSource.sampling_frequency=2000000
SignalSource.freq=1575420000
SignalSource.gain=40
SignalSource.rf_gain=40
SignalSource.if_gain=30
SignalSource.AGC_enabled=false
SignalSource.samples=0
SignalSource.repeat=false
;# Next line enables the internal HackRF One bias (3.3 VDC)
SignalSource.osmosdr_args=hackrf,bias=1
SignalSource.enable_throttle_control=false
SignalSource.dump=false
;######### SIGNAL_SOURCE CONFIG ############



;######### SIGNAL_CONDITIONER CONFIG ############
SignalConditioner0.implementation=Signal_Conditioner
;SignalConditioner1.implementation=Signal_Conditioner
;SignalConditioner2.implementation=Signal_Conditioner

;######### DATA_TYPE_ADAPTER CONFIG ############
DataTypeAdapter0.implementation=Pass_Through
DataTypeAdapter1.implementation=Pass_Through
DataTypeAdapter2.implementation=Pass_Through

;######### INPUT_FILTER CONFIG ############
InputFilter0.implementation=Freq_Xlating_Fir_Filter
InputFilter0.decimation_factor=7
InputFilter0.input_item_type=gr_complex
InputFilter0.output_item_type=gr_complex
InputFilter0.taps_item_type=float
InputFilter0.filter_type=lowpass
InputFilter0.bw=7000000
InputFilter0.tw=500000
InputFilter0.IF=-22902000
InputFilter0.sampling_frequency=56000000
InputFilter0.dump=false
InputFilter0.dump_filename=../data/input_filter.dat

;######### INPUT_FILTER CONFIG ############
InputFilter1.implementation=Freq_Xlating_Fir_Filter
InputFilter1.decimation_factor=7
InputFilter1.input_item_type=gr_complex
InputFilter1.output_item_type=gr_complex
InputFilter1.taps_item_type=float
InputFilter1.filter_type=lowpass
InputFilter1.bw=7000000
InputFilter1.tw=500000
InputFilter1.IF=-8580000
InputFilter1.sampling_frequency=56000000
InputFilter1.dump=false
InputFilter1.dump_filename=../data/input_filter.dat

;######### INPUT_FILTER CONFIG ############
InputFilter2.implementation=Freq_Xlating_Fir_Filter
InputFilter2.decimation_factor=7
InputFilter2.input_item_type=gr_complex
InputFilter2.output_item_type=gr_complex
InputFilter2.taps_item_type=float
InputFilter2.filter_type=lowpass
InputFilter2.bw=7000000
InputFilter2.tw=500000
InputFilter2.IF=18000000
InputFilter2.sampling_frequency=56000000
InputFilter2.dump=false
InputFilter2.dump_filename=../data/input_filter.dat

;######### RESAMPLER CONFIG ############
Resampler0.implementation=Pass_Through
Resampler1.implementation=Pass_Through
Resampler2.implementation=Pass_Through

;######### CHANNELS GLOBAL CONFIG ############
Channels_1B.count=10
Channels_1C.count=10
Channels_B1.count=14
Channels_1G.count=8

Channels_1B.RF_channel_ID=1
Channels_1C.RF_channel_ID=0
Channels_B1.RF_channel_ID=0
Channels_1G.RF_channel_ID=2


Channels.in_acquisition=2

;######### ACQUISITION BEIDOU CONFIG ############
Acquisition_B1.implementation=BEIDOU_B1I_PCPS_Acquisition
Acquisition_B1.item_type=gr_complex
Acquisition_B1.coherent_integration_time_ms=2
;Acquisition_B1.max_dwells=2
;Acquisition_B1.pfa=0.02
Acquisition_B1.pfa=0.000002
Acquisition_B1.doppler_max=6000
Acquisition_B1.doppler_step=100
Acquisition_B1.dump=false
Acquisition_B1.dump_filename=./bds_acq
;Acquisition_B1.blocking=true
Acquisition_B1.bit_transition_flag = false;

;######### ACQUISITION GPS CONFIG ############
Acquisition_1C.implementation=GPS_L1_CA_PCPS_Acquisition
Acquisition_1C.item_type=gr_complex
Acquisition_1C.coherent_integration_time_ms=1
Acquisition_1C.pfa=0.015
Acquisition_1C.doppler_max=6000
Acquisition_1C.doppler_step=200
Acquisition_1C.max_dwells=4
;Acquisition_1C.blocking=true
Acquisition_1C.dump=false
Acquisition_1C.dump_filename=./acq_dump.dat

;######### ACQUISITION GALILEO CONFIG ############
Acquisition_1B.implementation=Galileo_E1_PCPS_Ambiguous_Acquisition
Acquisition_1B.coherent_integration_time_ms=2
;Acquisition_1B.pfa=0.000008
Acquisition_1B.pfa=0.025
Acquisition_1B.doppler_max=6000
Acquisition_1B.doppler_step=200
Acquisition_1B.max_dwells=4
;Acquisition_1B.repeat_satellite=true
Acquisition_1B.cboc=true
;Acquisition_1B.blocking=true
Acquisition_1B.dump=false
Acquisition_1B.dump_filename=./acq_dump.dat

;######### ACQUISITION GLONASS CONFIG ############
Acquisition_1G.implementation=GLONASS_L1_CA_PCPS_Acquisition
Acquisition_1G.item_type=gr_complex
Acquisition_1G.coherent_integration_time_ms=1
Acquisition_1G.max_dwells=4
Acquisition_1G.pfa=0.02
Acquisition_1G.doppler_max=6000
Acquisition_1G.doppler_step=100
Acquisition_1G.dump=false
Acquisition_1G.dump_filename=./G1_acq



;######### TRACKING BEIDOU CONFIG ############
Tracking_B1.implementation=BEIDOU_B1I_DLL_PLL_Tracking
Tracking_B1.item_type=gr_complex
Tracking_B1.extend_correlation_symbols=10
Tracking_B1.pll_bw_hz=50.0
Tracking_B1.dll_bw_hz=2.00
Tracking_B1.pll_bw_narrow_hz=15.0
Tracking_B1.dll_bw_narrow_hz=1.50
;Tracking_B1.cn0_min=20
;Tracking_B1.fll_bw_hz=20
;Tracking_B1.enable_fll_pull_in=true
;Tracking_B1.enable_fll_steady_state=false
Tracking_B1.dump=false
Tracking_B1.dump_filename=./epl_tracking_ch_

;######### TRACKING GPS CONFIG ############
Tracking_1C.implementation=GPS_L1_CA_DLL_PLL_Tracking
Tracking_1C.item_type=gr_complex
Tracking_1C.extend_correlation_symbols=10
Tracking_1C.early_late_space_chips=0.5
Tracking_1C.early_late_space_narrow_chips=0.15
Tracking_1C.pll_bw_hz=30.0
Tracking_1C.dll_bw_hz=2.0
Tracking_1C.pll_bw_narrow_hz=10.0
Tracking_1C.dll_bw_narrow_hz=1.50
Tracking_1C.fll_bw_hz=10
Tracking_1C.enable_fll_pull_in=true
Tracking_1C.enable_fll_steady_state=false
Tracking_1C.dump=false
Tracking_1C.dump_filename=tracking_ch_

;######### TRACKING GALILEO CONFIG ############
Tracking_1B.implementation=Galileo_E1_DLL_PLL_VEML_Tracking
Tracking_1B.extend_correlation_symbols=4
Tracking_1B.item_type=gr_complex
Tracking_1B.pll_bw_hz=30.0
Tracking_1B.dll_bw_hz=2.0
Tracking_1B.pll_bw_narrow_hz=20.0
Tracking_1B.dll_bw_narrow_hz=1.50
Tracking_1B.track_pilot=true
Tracking_1B.enable_fll_pull_in=true;
Tracking_1B.enable_fll_steady_state=false
Tracking_1B.fll_bw_hz=20

;######### TRACKING GLONASS CONFIG ############
Tracking_1G.implementation=GLONASS_L1_CA_DLL_PLL_C_Aid_Tracking
Tracking_1G.item_type=gr_complex
Tracking_1G.pll_bw_hz=40
Tracking_1G.dll_bw_hz=2.5
Tracking_1G.extend_correlation_ms=1
Tracking_1G.pll_bw_narrow_hz=20
Tracking_1G.dll_bw_narrow_hz=1.5
Tracking_1G.dump=false
Tracking_1G.dump_filename=./epl_tracking_ch_



;######### TELEMETRY DECODER BEIDOU CONFIG ############
TelemetryDecoder_B1.implementation=BEIDOU_B1I_Telemetry_Decoder
TelemetryDecoder_B1.dump=false

;######### TELEMETRY DECODER GPS CONFIG ############
TelemetryDecoder_1C.implementation=GPS_L1_CA_Telemetry_Decoder
TelemetryDecoder_1C.dump=false

;######### TELEMETRY DECODER GALILEO E1B CONFIG ############
TelemetryDecoder_1B.implementation=Galileo_E1B_Telemetry_Decoder
TelemetryDecoder_1B.dump=false

;######### TELEMETRY DECODER GLONASS CONFIG ############
TelemetryDecoder_1G.implementation=GLONASS_L1_CA_Telemetry_Decoder
TelemetryDecoder_1G.dump=false


;######### OBSERVABLES CONFIG ############
Observables.implementation=Hybrid_Observables
Observables.dump=false
Observables.dump_filename=./observables.dat

;######### PVT CONFIG ############
PVT.implementation=RTKLIB_PVT
PVT.threshold_reject_GDOP=100
PVT.elevation_mask=3
PVT.raim_fde=1
PVT.positioning_mode=Single  ; options: Single, Static, Kinematic, PPP_Static, PPP_Kinematic
PVT.iono_model=Broadcast ; options: OFF, Broadcast, SBAS, Iono-Free-LC, Estimate_STEC, IONEX
PVT.trop_model=Saastamoinen ; options: OFF, Saastamoinen, SBAS, Estimate_ZTD, Estimate_ZTD_Grad
PVT.output_rate_ms=100
PVT.display_rate_ms=500
PVT.enable_rx_clock_correction=true
PVT.flag_rtcm_server=true
PVT.flag_rtcm_tty_port=false
PVT.rtcm_dump_devname=/dev/pts/1
PVT.rtcm_tcp_port=2101
PVT.rtcm_MT1019_rate_ms=5000
PVT.rtcm_MT1077_rate_ms=1000
PVT.rinex_version=2
PVT.flag_nmea_tty_port=true
PVT.nmea_dump_devname=/dev/pts/3

; To use gpsd with GNSS-SDR
; 1. run socat -d -d pty,raw,echo=0 pty,raw,echo=0
; 2. Set PVT.nmea_dump_devname to first PTY from socat output
; 3. run gpsd -b -n -N /dev/pts/4
; where /dev/pts/4 is the second PTY from socat output
; 4. run some gpsd client (xgps or other)



PVT.enable_monitor=true
PVT.monitor_client_addresses=127.0.0.1
PVT.monitor_udp_port=1111

Monitor.enable_monitor=true
Monitor.decimation_factor=4
Monitor.client_addresses=127.0.0.1
Monitor.udp_port=1112

;AcquisitionMonitor.enable_monitor=true
AcquisitionMonitor.client_addresses=127.0.0.1
AcquisitionMonitor.udp_port=1112
