### ISSUE TITLE
Receive GPS data error!!

### ISSUE THREAD

**Issue by CodoonAutomatedTest** [gnss-sdr/gnss-sdr#133]
from gps sdr simulation, I could transmitting using hackrf One.it is transmitting well and i could receive the signals well, but when I used GPS Data application on HUAWEI Android phone(Kirin CPU). The GPS Data is different from another phone, The receive data is not available for data transmission. how can i probably fix?

**Comment by mmajoral** [comment]
From your question we understand you would like to re-transmit the received GNSS signals ? This is not possible with GNSS-SDR, since it does not regenerate the received signals.
