### ISSUE TITLE
Can I use GUI instead of command line when building and running projects？

### ISSUE THREAD

**Issue by samwiseyu** [gnss-sdr/gnss-sdr#136]
I find there is a 'GUI' branch in gnss-sdr repository. Is it the GUI for building and running GNSS-SDR projects? Can I use it instead of command line?

Thank you very much!

**Comment by carlesfernandez** [comment]
Dear samwiseyu,

the gui branch is still not ready and the GUI is not usable in its current
state. We will continue working on that (actually, it is an idea proposed
for this year's GSoC), but more development is needed before you can use it.

Best regards,
Carles

**Comment by samwiseyu** [comment]
Dear Carles

Thank you very much for your reply. Looking forword to see the new GUI version. 

Best regards,
Samwise
