### ISSUE TITLE
program doesn't launch reliably

### ISSUE THREAD

**Issue by cybernard** [gnss-sdr/gnss-sdr#180]
*** Error in `./gnss-sdr': corrupted double-linked list: 0x02464da8 ***
Aborted
*** Error in `./gnss-sdr': corrupted double-linked list: 0x00c59e60 ***
Aborted
Segmentation fault
corrupted double link x2
Segmentation fault
Segmentation fault

It took 15 launches to get it to run 1 time.

When it does run, it can't get a signal lock.
It finds dozens of satellites, but it can lock on any of them.

```
Current receiver time: 14 min 21 s
Tracking of GPS L1 C/A signal started on channel 0 for satellite GPS PRN 25 (Block IIF)
Loss of lock in channel 2!
Loss of lock in channel 3!
Tracking of GPS L1 C/A signal started on channel 6 for satellite GPS PRN 29 (Block IIR-M)
Loss of lock in channel 1!
OTracking of GPS L1 C/A signal started on channel 2 for satellite GPS PRN 30 (Block IIF)
Current receiver time: 14 min 22 s
Tracking of GPS L1 C/A signal started on channel 1 for satellite GPS PRN 18 (Block IIR)
Loss of lock in channel 4!
Loss of lock in channel 5!
```

I let this run for 8 hours like this and still no lock.  I have a RTL-SDR connected to a raspberry pi 3.

Also this supposed to use +300% of the CPU all the time.  This program needs to go on a diet.  I just want a GPS position, and not any fancy extras.

**Comment by mmajoral** [comment]
The Raspberry pi 3 is not suitable for running GNSS-SDR in real time. You need a more powerful processor.
