### ISSUE TITLE
How to save raw GPS Navigation message(50 Hz, parity included) to a file?

### ISSUE THREAD

**Issue by ahmadhassan9651** [gnss-sdr/gnss-sdr#197]
I am trying to save the RAW GPS NAVIGATION MESSAGE(complete subframes) to a file in realtime mode.
I tried to read tracking dump file using matlab scripts in utils folder. The prompt inphase vector in GNSS tracking struct is the nav message but its upsampled. 
I think the telemetry decoder reads and decodes the navigation message provided by tracking output.
so i request if there is any way or what changes to be made in the program to save raw nav message subframes to a file?
Kindly Help!

**Comment by mmajoral** [comment]
This feature has been implemented in GNSS-SDR. Please, refer to [this link](https://gnss-sdr.org/docs/sp-blocks/telemetry-decoder/#retrieving-decoded-navigation-messages).
