### ISSUE TITLE
Unable to get a fix with kf block after 388d162

### ISSUE THREAD

**Issue by glamountain** [gnss-sdr/gnss-sdr#208]
Something about this commit makes it impossible to get a position fix with the kalman filter block using the 2013_04_04_GNSS_SIGNAL_at_CTTC_SPAIN dataset. A couple points:

- Able to get a fix on commit a833abb
- **Not** able to get a fix on commit 388d162 or any subsequent commits
- Disabling the bayesian filtering functionality by way of the associated config parameter **does not** allow a fix to be obtained
- Entirely removing references to the bayesian estimator library from the kalman filter gnuradio block **does not** allow a fix to be obtained
- ~~Reverting 388d162 on the latest version of the [next](https://github.com/gnss-sdr/gnss-sdr/tree/next) branch (8382569 on 09/05/2018) **does** allow a fix to be obtained.~~ EDIT: not clear if this is true

**Comment by carlesfernandez** [comment]
Hi @glamountain 

I’ve seen that I’ve messed up the KF implementation, sorry about that. It seems that the passing by reference using armadillo is trickier than I thought. I’ll fix it ASAP.

I also plan to include a test of the implementation that will be routinely executed each time we do a new commit to the repository, so if someone breaks it again, we will notice it immediately.

Best,
Carles

**Comment by glamountain** [comment]
@carlesfernandez I think I might have been misunderstanding what's going on. There might be a change to how the PVT block displays/logs results that I wasn't familiar with since I was working off the KF branch instead of the next branch during GSoC. There is likely not anything wrong with the KF block. I'll close the ticket.

I'm working on a few different Kalman implemetations and I have a couple questions. I'll send you those in an email soon instead, so please look out for that.
