### ISSUE TITLE
Failed to build make file on EI Captain

### ISSUE THREAD

**Issue by tomfisher** [gnss-sdr/gnss-sdr#21]
Hi, I am trying to build gnss-sdr on EI Captain. When ```cmake ../```, I got the following error:

```
-- gflags library found at /usr/local/lib/libgflags.dylib
-- Looking for OpenSSL instead...
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_INCLUDE_DIR) 
 The GnuTLS library with openssl compatibility enabled has not been found.
 You can try to install the required libraries by typing:
 sudo port install gnutls
CMake Error at CMakeLists.txt:819 (message):
  GnuTLS libraries with openssl compatibility are required to build gnss-sdr
```

I did follow the instructions on Mac and installed required libraries with Homebrew.

**Comment by carlesfernandez** [comment]
Hi Tom,

gnss-sdr can link against OpenSSL, GnuTLS or LibreSSL. Try to install one of those with homebrew:

~~~~~~ 
$ brew install openssl
~~~~~~ 

or 

~~~~~~ 
$ brew install gnutls
~~~~~~ 
or 

~~~~~~ 
$ brew install libressl
~~~~~~ 

Instructions in the README file have been updated to reflect that missing dependency (see 0eb8537f52287539447ca35a954d10f437dd88e4). Thanks for spotting it,

Carles
