### ISSUE TITLE
Stereo V2 L1L2conf ?

### ISSUE THREAD

**Issue by yealwang** [gnss-sdr/gnss-sdr#212]
I have collect L1L2 signal data by NSL Stereo V2. SF 26Mhz, IF 6.5Mhz fro L1 and IF 0 Mhz for L2, how to write the config for the L2? 
Setting GNSS-SDR.internal_fs_sps=6500000?
Do you already have an configure for the NSL front-end?

**Comment by 1039962658** [comment]
Hi, do you have the NSL Stereo V2, and where did you buy?

**Comment by yealwang** [comment]
Hi
I buy it 4 years ago on their UK web

发自我的iPhone

在 2020年8月7日，17:25，pyang_15 <notifications@github.com> 写道：

﻿

Hi, do you have the NSL Stereo V2, and where did you buy?

**Comment by 1039962658** [comment]
Thank you for your reply. 
I have browsed their web, and it is no longer available for sale. 
Are you chinese?

**Comment by yealwang** [comment]
yeah， I am Chinese, I donot know that

发自我的iPhone

在 2020年8月7日，17:39，pyang_15 <notifications@github.com> 写道：

﻿

Thank you for your reply.
I have browsed their web, and it is no longer available for sale.
Are you chinese?
