### ISSUE TITLE
Signal acquisition stop working randomly and drives GNSS-SDR  to loose all satellites

### ISSUE THREAD

**Issue by Arribas** [gnss-sdr/gnss-sdr#22]
This bug that randomly appear was reported internally by the GNSS-SDR team long time ago. The visible symtom is that GNSS-SDR often looses all tracking satellites and apparently the acquisition process can not recover any new satellite. The bug was observed several times when GNSS-SDR is working in real-time for long runtimes (i.e. run times grater than 120 minutes).

I finally managed to reproduce the bug in post processing mode: 

Here you can see the output log for a single channel GPS L1 receiver:

javier@pcjarribas:~/git/gnss-sdr/build$ ../install/gnss-sdr --config_file=../conf/gnss-sdr_Hybrid_nsr.conf
linux; GNU C++ version 4.8.4; Boost_105400; UHD_003.010.git-113-g6b367da7

Initializing GNSS-SDR v0.0.6.git-next-1bafa1e ... Please wait.
Logging will be done at "/tmp"
Use gnss-sdr --log_dir=/path/to/log to change that.
Processing file /media/javier/SISTEMA/signals/ifen/E1L1_FE0_Band0.stream, which contains 1500195840 [bytes]
GNSS signal recorded time to be processed: 293.005 [s]
Using Volk machine: avx2_64_mmx
connected
**n acq=27.43444061279297
n acq=12.60478496551514**
**Current input signal time = 1 [s]
Current input signal time = 2 [s]
Current input signal time = 3 [s]
Current input signal time = 4 [s]
Current input signal time = 5 [s]
Current input signal time = 6 [s]
Current input signal time = 7 [s]
Current input signal time = 8 [s]
Current input signal time = 9 [s]
Current input signal time = 10 [s]
Current input signal time = 11 [s]
Current input signal time = 12 [s]
Current input signal time = 13 [s]
Current input signal time = 14 [s]
Current input signal time = 15 [s]
Current input signal time = 16 [s]
Current input signal time = 17 [s]
Current input signal time = 18 [s]
Current input signal time = 19 [s]
Current input signal time = 20 [s]
Current input signal time = 21 [s]
Current input signal time = 22 [s]
qCurrent input signal time = 23 [s]
**
Quit keystroke order received, stopping GNSS-SDR !!
Stopping GNSS-SDR, please wait!
Total GNSS-SDR run time 2.450165 [seconds]
GNSS-SDR program ended.

I have added a simple debug print in PCPS_acquisition_cc to show the acquisition threshold in the console, printed each time that acquisition fails. Apparently, after two negative acquisitions, the acquisition scheduler is not activating acquisition anymore, even there is a tracking channel available. As a consequence, GNSS-SDR is doing nothing, not acquiring nor tracking any satellite. The bug is related to the control_thread that dispatches satellites to acquisition and tracking (80%) or may be it involves some bug in the PCPS acquisition module internal state machine (20%).

**Comment by carlesfernandez** [comment]
Workaround pushed in 833ca8ab8c9c2f48efe69bb20cd5f3592a7b8a08 

Now the receiver seems to work fine for more than 24 hours. Better solution is expected in the reworking of the message passing system.
