### ISSUE TITLE
Higher frequency RINEX?

### ISSUE THREAD

**Issue by matteocutugno** [gnss-sdr/gnss-sdr#228]
Hello to everyone,
is there a way to obtain RINEX observation and navigation files at a higher frequency than 1 Hz???
Maybe 10 Hertz or even higher?
I tried to modify some parameters of the PVT block but the SDR can't compute PVT. 
With the same .conf file i'm able to get PVT

Here is my PVT block

;######### PVT CONFIG ############
PVT.implementation=RTKLIB_PVT
PVT.positioning_mode=Single
PVT.output_rate_ms=10000
PVT.display_rate_ms=10000
PVT.iono_model=Broadcast
PVT.trop_model=Saastamoinen
PVT.flag_rtcm_server=false
PVT.flag_rtcm_tty_port=false
PVT.rtcm_dump_devname=/dev/pts/1
PVT.rtcm_tcp_port=2101
PVT.rtcm_MT1019_rate_ms=5000
PVT.rtcm_MT1077_rate_ms=1000
PVT.rinex_version=2
PVT.rinexobs_rate_ms=10000
PVT.rinexnav_rate_ms=10000
PVT.dump=true
PVT.dump_filename=./PVT
PVT.dump_mat=true

Thank you all
MC

**Comment by sergey-nik** [comment]
Hi,
Briefly, in order to get the RINEX output working at the rate of 10Hz, the corresponding parameters ("rinexobs_rate_ms" and "rinexnav_rate_ms") should be set to 100ms.

But there is one important thing. The parameter "output_rate_ms" is the cornerstone. It defines the rate at which the PVT block performs the computation of a PVT-solution. Further, if (and only if) the PVT-solution is computed, the block proceeds to printing of positions, saving observations, navigation data etc. Thus, the value of "output_rate_ms" should be at least equal (or even less) to the minimum of other rates. Also it is important that other rates are multiple of "output_rate_ms".

As a summary, I would suggest to try the following values:
PVT.output_rate_ms=20 ; the computation of PVT is performed internally at 50Hz
PVT.rinexobs_rate_ms=100 ; the observations are saved at 10Hz (every 5th computation)
PVT.rinexnav_rate_ms=100 ; the observations are saved at 10Hz (every 5th computation)
PVT.display_rate_ms=500 ; positions are printed to a console at 2Hz (every 25th computation)

**Comment by matteocutugno** [comment]
Hi,
i tried with @sergey-nik advices.
PVT.output_rate_ms=20; 
PVT.rinexobs_rate_ms=100; 
PVT.rinexnav_rate_ms=100 
With such parameters i was able to get Rinex files at 10 Hz with no problems.

Then i tried to get Rinex at 100 Hz using the following parameters: 
PVT.output_rate_ms=10;  the computation of PVT might be performed internally at 100Hz
PVT.rinexobs_rate_ms=10;  the observations are saved at 100Hz  (every computation)
PVT.rinexnav_rate_ms=10;  the observations are saved at 100Hz (every computation)

The result was that GNSS-SDR computes PVT at 50 Hz.
Here's a part of my rinex observation file:

-------------------------------------------------------------------------------------------------------------------
     3.02           OBSERVATION DATA    G                   RINEX VERSION / TYPE
G = GPS  R = GLONASS  E = GALILEO  S = GEO  M = MIXED       COMMENT             
GNSS-SDR            matteo              20181217 094330 UTC PGM / RUN BY / DATE 
GPS OBSERVATION DATA FILE GENERATED BY GNSS-SDR             COMMENT             
GNSS-SDR VERSION 0.0.9.git-next-f3e32e30                    COMMENT             
See https://gnss-sdr.org                                    COMMENT             
DEFAULT MARKER NAME                                         MARKER NAME         
matteo              CTTC                                    OBSERVER / AGENCY   
GNSS-SDR            Software Receiver   0.0.9.git           REC # / TYPE / VERS 
Antenna number      Antenna type                            ANT # / TYPE        
        0.0000        0.0000        0.0000                  APPROX POSITION XYZ 
        0.0000        0.0000        0.0000                  ANTENNA: DELTA H/E/N
G    4 C1C L1C D1C S1C                                      SYS / # / OBS TYPES 
DBHZ                                                        SIGNAL STRENGTH UNIT
  2018    12    17    09    43   48.0800000     GPS         TIME OF FIRST OBS   
    18    18   137     7                                    LEAP SECONDS        
                                                            END OF HEADER       
> 2018 12 17 09 43 48.0800000  0  4                                             
G09  18088294.193 6   -578223.529 6      1515.842 6        40.147               
G03  18275814.588 6    548951.557 6     -1544.306 6        38.326               
G06  19608743.139 6   -209558.634 6      2467.039 6        36.466               
G23  17907477.201 6     89023.018 6      -274.688 6        37.407               
> 2018 12 17 09 43 48.1000000  0  4                                             
G09  18088288.645 6   -578253.976 6      1522.319 6        41.678               
G03  18275821.655 6    548982.004 6     -1538.967 6        38.932               
G06  19608734.137 6   -209607.972 6      2463.798 6        38.197               
G23  17907480.217 5     89028.426 5      -277.626 5        34.592               
> 2018 12 17 09 43 48.1200000  0  4                                             
G09  18088282.127 6   -578284.397 6      1505.053 6        40.786               
G03  18275827.869 6    549012.551 6     -1576.751 6        40.123               
G06  19608724.466 6   -209657.269 6      2487.028 6        36.216               
G23  17907482.321 6     89033.895 6      -259.938 6        37.296               
> 2018 12 17 09 43 48.1400000  0  4                                             
G09  18088277.133 6   -578314.802 6      1523.124 6        40.062               
G03  18275834.253 6    549042.996 6     -1531.080 6        38.685               
G06  19608715.594 6   -209706.492 6      2466.220 6        38.634               
G23  17907483.786 6     89039.329 6      -274.801 6        37.296               
> 2018 12 17 09 43 48.1600000  0  4                                
-------------------------------------------------------------------------------------------------------------------
As you can see the rate of the Rinex observation file is 50 Hz because the time interval between two measure is 0,02 sec.
I didn't understand why the output is 50 Hz instead of 100 Hz.

Thanks in advance for any help.
