### ISSUE TITLE
Fix for Galileo F/NAV messages decoding (patch included)

### ISSUE THREAD

**Issue by sergey-nik** [gnss-sdr/gnss-sdr#229]
Hi.

We were trying to obtain a position fix with Galileo E5, but the results were not correct. Eventually our investigations led us to checking the definition of message structure used in the telemetry decoder. There were several mismatches with the specification, which affected the ephemeris parameters and the GST-UTC conversion.

Briefly, some of the parameters were decoded as unsigned integers, whereas they should have been signed integers.

Please, find the attached patch file.

[gal_FNAV_decoding.txt](https://github.com/gnss-sdr/gnss-sdr/files/2675337/gal_FNAV_decoding.txt)

The documentation we used is:
OS SIS ICD, Issue 1.2, January 2015

Regards.

**Comment by carlesfernandez** [comment]
Applied in 63e90f8, plus the same change in the variable FNAV_M0_2 (mean anomaly at reference time), which is also signed according to the ICD. Thanks for spotting this issue!
