### ISSUE TITLE
How to get the "File Signal Source"?

### ISSUE THREAD

**Issue by iknow34languages** [gnss-sdr/gnss-sdr#237]
Hi,

    i am a newer to GNSS

i saw that there is many signal source we can choose

where can i download the "File signal source"?

Thanks

**Comment by matteocutugno** [comment]
Hi,
if you are new to GNSS-SDR my first advice is to follow the tutorial my first position fix that you can find on the official website (https://gnss-sdr.org/my-first-fix/). There you can download a GNSS signal sample and try to post process it.
MC

**Comment by iknow34languages** [comment]
@matteocutugno Thanks

**Comment by iknow34languages** [comment]
@matteocutugno close the case thanks
