### ISSUE TITLE
Where is the "volk_gnsssdr_32f_index_max_32u" definition?

### ISSUE THREAD

**Issue by iknow34languages** [gnss-sdr/gnss-sdr#242]
From file:
pcps_acquisition.cpp

There is 

...
    // Find the correlation peak and the carrier frequency
    for (uint32_t i = 0; i < num_doppler_bins; i++)
        {
            volk_gnsssdr_32f_index_max_32u(&tmp_intex_t, d_magnitude_grid[i], d_fft_size);
            if (d_magnitude_grid[i][tmp_intex_t] > grid_maximum)
                {
                    grid_maximum = d_magnitude_grid[i][tmp_intex_t];
                    index_doppler = i;
                    index_time = tmp_intex_t;
                }
        }
...

I can  not find the definition of the function : volk_gnsssdr_32f_index_max_32u

**Comment by carlesfernandez** [comment]
Here it is: [volk_gnsssdr_32f_index_max_32u.h](https://github.com/gnss-sdr/gnss-sdr/blob/master/src/algorithms/libs/volk_gnsssdr_module/volk_gnsssdr/kernels/volk_gnsssdr/volk_gnsssdr_32f_index_max_32u.h)
