### ISSUE TITLE
How to get the process of "general_work"?

### ISSUE THREAD

**Issue by iknow34languages** [gnss-sdr/gnss-sdr#246]
From the code:

 i see many function as follows:

### int xxxxxxxxxx::general_work(...)

and from the start ,these function will be called:

**E0125 23:18:14.056072 97321 dll_pll_veml_tracking.cc:1338] dll_pll_veml_tracking::general_work  d_state :  0
E0125 23:18:14.056155 97318 dll_pll_veml_tracking.cc:1338] dll_pll_veml_tracking::general_work  d_state :  0
E0125 23:18:14.056218 97315 dll_pll_veml_tracking.cc:1338] dll_pll_veml_tracking::general_work  d_state :  0
E0125 23:18:14.056279 97312 dll_pll_veml_tracking.cc:1338] dll_pll_veml_tracking::general_work  d_state :  0
E0125 23:18:14.056524 97324 dll_pll_veml_tracking.cc:1338] dll_pll_veml_tracking::general_work  d_state :  2
E0125 23:18:14.056823 97330 dll_pll_veml_tracking.cc:1338] dll_pll_veml_tracking::general_work  d_state :  0
E0125 23:18:14.056885 97327 dll_pll_veml_tracking.cc:1338] dll_pll_veml_tracking::general_work  d_state :  0**

But i don't know where and when to start to  call these function.

Who can show me the top level interface to call these  function?

EG:
A->b->c->D-> xxxxx:: general_work;

I can not find the A  or B step;

Thanks

**Comment by carlesfernandez** [comment]
The GNU Radio scheduler will call them for you. Please check https://gnss-sdr.org/docs/fundamentals/ for an introduction on how this works,
