### ISSUE TITLE
minimum boost version

### ISSUE THREAD

**Issue by jsngross** [gnss-sdr/gnss-sdr#247]
Hi, The minimum boost version should be updated in the CMakeLists.txt  file. I had an outdated boost version installed (1.55). While it passed the CMakeLists chech, which looked for versions >1.45 master/next/latest release would not compile due to an outdated boost serialization library reference. After upgrading to a newer boost, it compiled.

**Comment by carlesfernandez** [comment]
Dear @jsngross,

you are right that the minimum Boost version was too low, and it has been set up to 1.53 in the `next` branch, which is the minimum version tested in our Continuous Integration system.


The software builds fine usign Boost 1.53 (e.g., in Centos 7, see   https://gitlab.com/gnss-sdr/gnss-sdr/-/jobs/156243203), Boost 1.54 (e.g., Ubuntu 14.04, see https://gitlab.com/gnss-sdr/gnss-sdr/-/jobs/156243219) and Boost 1.55 (e.g., Debian 8.10, see https://gitlab.com/gnss-sdr/gnss-sdr/-/jobs/156243207) 

Which operating system are you working with? I can’t reproduce the problems you had with Boost 1.55

Thanks,
Carles
