### ISSUE TITLE
pcps_acquisition_cc::set_local_code

### ISSUE THREAD

**Issue by mmajoral** [gnss-sdr/gnss-sdr#25]
The function pcps_acquisition_cc::set_local_code only copies the first 1 ms of data of the pre-computed code samples to the d_fft_if input buffer without taking into account the configuration data.

If the correlation of the acquisition is done using 1 ms then this is ok. 

But if the correlation is done using more than 1 ms then there are missing samples in the fft input. The energy of the correlation will not grow according to the integration time.

This has been checked by testing the acquisition using 1 ms, 2 ms and 4 ms with and without the bug fix.

**Comment by luis-esteve** [comment]
Bug fixed, I close the issue
