### ISSUE TITLE
FIR or IIR?

### ISSUE THREAD

**Issue by johnwstanford** [gnss-sdr/gnss-sdr#269]
Not a big deal, but I think this should say IIR, not FIR.  An FIR depends depends only on a finite number of the most recent inputs (finite impulse response), whereas an IIR (infinite impulse response) filter depends recursively on its own output like this one does.  I attached a block diagram that, I think, represents this filter.  

x(n) represents `PLL_discriminator`
y(n) represents `carr_nco`
k1 represents `d_tau2_carr/d_tau1_carr`
k2 represents `d_pdi_carr / (2.0 * d_tau1_carr)`

https://github.com/gnss-sdr/gnss-sdr/blob/31c6b6bc1da77c9589a04d52a38d2d20edacf06e/src/algorithms/tracking/libs/tracking_2nd_PLL_filter.cc#L67

![Screenshot from 2019-04-30 22-45-58](https://user-images.githubusercontent.com/16873431/57005026-db9a4680-6b99-11e9-8c2a-d069d54a9db0.png)

**Comment by carlesfernandez** [comment]
Thanks, you are right. Corrected.
