### ISSUE TITLE
"next" branch performance

### ISSUE THREAD

**Issue by JJZim** [gnss-sdr/gnss-sdr#27]
Hello,
I'm currently trying to use the version in "next" branch.
After using it a while it seems that the performance significantly decreased in comparison to the 0.0.6 release.

For example, on a machine with a Core i7 CPU and a X300 USRP I was able to easily run 8 channels in parallel. There were no (or negligible amount of) overflows ("O") or drops ("D") on the USRP/Host.
Now, after updating to the "next" branch (commit: 31ae25cb83a1f76ff17f12c65b310c54275a826a), I get lots of drops on the host and, in addition, the tracking algorithm seems to perform worse than before which leads to no or only sporadic position fixes.

I'm using the multichannel X300 realtime config with 8 channels (4 on each subdevice), all set to GPS L1 tracking with PCPS acquisition.

Regards,
Jan

**Comment by carlesfernandez** [comment]
That commit seems not related to receiver's performance, it's only executed when exiting the program. Please execute ```volk_profile``` and ```volk_gnsssdr_profile``` to take advantage of the best SIMD acceleration in your machine.
