### ISSUE TITLE
Building from master incorrectly assumes GNU Radio 3.8

### ISSUE THREAD

**Issue by karel** [gnss-sdr/gnss-sdr#281]
The CMake configuration files incorrectly assume that GNU Radio 3.8 is installed when actually the latest 3.7 release [3.7.13.5](https://github.com/gnuradio/gnuradio/releases/tag/v3.7.13.5) is present in the system. This results in build errors of course.

https://github.com/gnss-sdr/gnss-sdr/blob/31c6b6bc1da77c9589a04d52a38d2d20edacf06e/src/algorithms/resampler/adapters/CMakeLists.txt#L40-L42

https://github.com/gnss-sdr/gnss-sdr/blob/31c6b6bc1da77c9589a04d52a38d2d20edacf06e/src/algorithms/input_filter/adapters/CMakeLists.txt#L49-L51

https://github.com/gnss-sdr/gnss-sdr/blob/31c6b6bc1da77c9589a04d52a38d2d20edacf06e/src/core/receiver/CMakeLists.txt#L122-L124

https://github.com/gnss-sdr/gnss-sdr/blob/31c6b6bc1da77c9589a04d52a38d2d20edacf06e/src/tests/CMakeLists.txt#L140-L142

**Comment by carlesfernandez** [comment]
Thanks for reporting this issue. This is fixed in 28907e1c22e170e7292633a4227830cc9262d12b (a quick, not a very elegant solution, but this is better handled in the CMake scripts of the `next` branch).
