### ISSUE TITLE
How to configure GNSS-SDR to output observables through TCP/IP ports?

### ISSUE THREAD

**Issue by shuwang1** [gnss-sdr/gnss-sdr#285]
I want to output GNSS-SDR observables to RTKlLIB through a TCP/IP port.  Something similar to what I can do with GNSS-SDRLIB, which allows you to output observables in RTCM through a TCP/IP port.

How can I achieve this? Is the step below sufficient?

`PVT.flag_rtcm_server=true ;PVT.rtcm_tcp_port=2101 ;PVT.rtcm_station_id=1234`

**Comment by carlesfernandez** [comment]
Yes. Any TCP client connecting to that IP address, at port 2101, should be receiving RTCM-104 messages, v3.2
