### ISSUE TITLE
How to add a new block into this project?

### ISSUE THREAD

**Issue by Supredan** [gnss-sdr/gnss-sdr#296]
in the configuration file,We know how to identify existing satellites,
For example, in the GPS L1 C/A configuration file, we can set it to 1C. 
`
;######### CHANNELS GLOBAL CONFIG ############  
Channels_1C.count=8  
Channels.in_acquisition=1  
Channel.signal=1C  
`
This is because the satellite signal has been defined in the gnss project, and now I have some modulation on the GPS signal. I hope to use the gnss project to process the signal, then I need to define a new satellite signal and write the corresponding signal processing module. If my satellite signal is called GPS_XX, then what part of the project should I make changes , so i can entering GPS_XX just like i i i enter 1C in the configuration file? and locate this signal?

**Comment by carlesfernandez** [comment]
What do you mean by "define a new satellite signal"? A new one invented by your own, just for the sake of research, or an existing one? 

The software can work with GPS L1 C/A (label `1C`), L2C (label `2S`) and L5 (label `L5`) signals, for all the existing GPS satellites.

If you want to add another kind of signal, you will need to write blocks for all the processing chain (Acquisition, Tracking, Telemetry Decoder, etc.). Please check the documentation and the existing examples.
