### ISSUE TITLE
Bug in Beidou_DNAV.h in D1_TGD2

### ISSUE THREAD

**Issue by DavidRamati** [gnss-sdr/gnss-sdr#320]
this is the current code:
`const std::vector<std::pair<int32_t, int32_t> > D1_TGD2({{121, 6}});`

while according to the ICD should be:
`const std::vector<std::pair<int32_t, int32_t> > D1_TGD2({{109, 4}, {121, 6}});`

ICD reference: http://en.beidou.gov.cn/SYSTEMS/ICD/201806/P020180608516798097666.pdf
BDS-SIS-ICD-B3I-1.0
Figure5-8Bit allocation for subframe 1 in format D1

**Comment by carlesfernandez** [comment]
Fixed in 9e79bb4
