### ISSUE TITLE
Bad normalization in pcps_acquisition

### ISSUE THREAD

**Issue by odrisci** [gnss-sdr/gnss-sdr#331]
The pcps acquisition block is a generic block providing non-coherent parallel code phase search. At the moment the normalization of the decision variable is incorrect (probably my fault when I added the non-blocking feature). For this reason it is not possible (at least in my experience) to write a generic configuration file for acquisition - each file needs to be tuned for the data set it processes in order to set the acquisition threshold in an appropriate manner.

The solution is fairly straightforward: the normalization can be computed by averaging the total power in a Doppler bin removed from the one containing the peak. The peak decision statistic is then divided by this power for a correct normalization.

There is one more issue then, that the current method of computing the decision threshold is based on the assumption that there is no non-coherent accumulation (max_dwells == 1). In fact it is straightforward again to extend the computation of the threshold to cases where max_dwells > 1.

In putting together a fix for this I've come across another issue: code duplication. In order to implement the fix for the threshold computation I have to modify every one of the individual adapters that adapts the pcps_acquisition class, and there are many. Most of this code is identical but has to be re-written for each class, making it very bug prone and hard to maintain.

I would suggest changing the structure of the acquisition classes a little bit as follows:

  1. The acq_conf class should be given a member function to set all its variables from a ConfigurationInterface. This would cut down on lots of the boilerplate in the acquisition adapaters (the same should be done for the dll_pll_conf class)
  2. The threshold computation should be done inside the gnuradio block (pcps_acquisition in this case) rather than in the adapter. I think this makes more sense as the gnuradio block implements the actual acquisition algorithm and so should have the knowledge on how to best compute the threshold.

**Comment by carlesfernandez** [comment]
Fix merged into the next branch at 82508e9aba50e56d0abfe3374ef3f0627eec5b90
