### ISSUE TITLE
Data type used for the file that is written to DMA

### ISSUE THREAD

**Issue by noelpedro** [gnss-sdr/gnss-sdr#365]
Hi can you guys tell me what data type is the file that gets written to the dma for the hardware accelerators found in the ad9361_fpga_signal_source.cc?

I’m thinking ibyte or ishort?

Thanks.

**Comment by mmajoral** [comment]
Hi noelpedro,
The HW works with files using the ibyte format.
Regards

**Comment by noelpedro** [comment]
Okay thanks I’ll get ibyte file from hack rf.

**Comment by noelpedro** [comment]
What device did you use  to capture 8 bit I and Q data file?
