### ISSUE TITLE
Linux/Windows performance

### ISSUE THREAD

**Issue by FraPorfi** [gnss-sdr/gnss-sdr#39]
Hi @carlesfernandez and @Arribas, I'm Francesco, the guy who wrote you by email address. I'm going to post questions here instead of annoying you by email. Sorry if I have written you by direct email message.

The questions that I made you were about performance. Why?
The objective would be to work with it on Windows, because it is more versatile as an operating system and because it is wide used. So, what I did?
First of all, since I was a little bit scared about task scheduling on Windows for future real-time implementations, I modified gnuradio framework to include just the core capabilities to allow the creation and execution of the flowgraph. So I obtained a simplified version of the core system. Afterwards, I decided to test it on Linux to check about real-time performance with my front end (Maxim2769), so I had to handle and work on the gnss-sdr code for generating the appropriate library and for creating the interface to communicate with it.

Then, I made some tests on Linux with the following configuration:
1) Dell mobile PC, Intel core i7, 2.8 GHz, quadcore, 8GB RAM
2) Ubuntu 16.04
3) GPS only, 6 channels, serial search acquisition, pcps fine doppler algorithm, 4MHz sampling frequency

I reported as a result a 20% CPU load (using Intel VTune Amplifier as a bottleneck analysis tool, if needed I can show you some screenshots). So, according to this result, I was wondering if you had the same kind of performance on Linux (or maybe I made some mistakes), and for this reason, thinking to use it in the future on Windows with the proper modifications, I was a bit scared that on Windows it could be worst since the higher CPU load due to the task scheduling.

Best regards,

Francesco

**Comment by carlesfernandez** [comment]
Hi Francesco,

it seems you are obtaining good results. You can find some [slides at overleaf](https://www.overleaf.com/articles/accelerating-gnss-software-receivers/ywcwtdjwgnky#.WGoHk7FDn3g) showing performance results we obtained using the software in four different platforms (using Linux and MacOS).
