### ISSUE TITLE
QUESTION FPGA ACQUISITION

### ISSUE THREAD

**Issue by noelpedro** [gnss-sdr/gnss-sdr#391]
Hi Guys,

Im trying to search for second peak for acquisition metric on the hardware.

How much if any of the acquisition grid did you store in BRAM?

The entitre 2-D grid? only a row at a time? none?

Thanks

Peter

**Comment by mmajoral** [comment]
Hi Peter,
There is not enough memory in the FPGA to store the the entire 2-D grid.
The acquisition runs a parallel code-phase search algorithm.
For each possible doppler frequency, the acquisition algorithm performs the following tasks:
- Perform the doppler wipeoff and compute the correlation between the received signal and the local copy of the PRN code. 
- Search for the peak values and peak positions in the correlation results.
During the doppler search, the results of the correlation are not stored, only the peak values and the peak positions  (first peak and second peak values) corresponding to the highest peak values that were found so far. At the end of the doppler search the results for the entire 2D grid are obtained without having to store the entire 2D grid.

Regards
Marc

**Comment by mmajoral** [comment]
Another possibility would be to use the external memory (SDRAM) to store the entire 2D grid.

**Comment by noelpedro** [comment]
Thanks

**Comment by noelpedro** [comment]
Hi Marc,

Is the raw signal stored in bram before performing Doppler wipeoff?

Noel
