### ISSUE TITLE
Overruns in Ubuntu After about 8min

### ISSUE THREAD

**Issue by AgileEngineeringLLC** [gnss-sdr/gnss-sdr#395]
I'm running Ubuntu 20.04 LTS on a new System76 Linux box. I built GNSS-SDR (next option) and am running a HackRF at 4MS/S. It acquires and tracks quickly, but after about 8 min I get overruns every time (see attached screenshot). I noticed on the screen shot that there's an RTKLIB error message that always proceeds the overrun start. 

Don

![overrun](https://user-images.githubusercontent.com/30239895/86376324-72eea400-bc4c-11ea-9a60-c592227bfd86.png)

**Comment by AgileEngineeringLLC** [comment]
Update: I re-built from next again and this time I'm not seeing the error.

**Comment by carlesfernandez** [comment]
Nice to know that it is working for you. This smells like an old bug that should be long gone. I was rechecking it when I saw your message.

**Comment by AgileEngineeringLLC** [comment]
It actually has started doing it again, latest run took 13 min. I'm running a hackrf at 4MS/S, so seems like it should be fine. I have a B200-mini coming next week, so I'm hoping the USRP interface is maybe more stable than the OSMOSDR interface. Don
