### ISSUE TITLE
Number of samples parameter ignored when too large

### ISSUE THREAD

**Issue by esqt** [gnss-sdr/gnss-sdr#396]
The parameter `samples` of the `File_Signal_Source` block is ignored (set to 0) when larger than 2^31-1 (the maximum of a 32-bits signed integer).

Consequently, if the number of samples specified is larger than 2^31-1, the file will be read until the end.

The problem comes from the following line, where an int32_t is returned:

https://github.com/gnss-sdr/gnss-sdr/blob/66a908fc42debcb7157acd773bccc056233bdc9a/src/algorithms/signal_source/adapters/file_signal_source.cc#L44

https://github.com/gnss-sdr/gnss-sdr/blob/66a908fc42debcb7157acd773bccc056233bdc9a/src/core/interfaces/configuration_interface.h#L49

Using the overloaded function which returns a 64-bits unsigned integer solves this issue:
`samples_ = configuration->property(role + ".samples", (uint64_t)0);`

**Comment by carlesfernandez** [comment]
Thanks! Fixed in fb8e5e5
