### ISSUE TITLE
Down sampling fo  AD 9361 FPGA signal source.

### ISSUE THREAD

**Issue by noelpedro** [gnss-sdr/gnss-sdr#399]
Hi,

Do you guys down sample for acquisition on the hardware when using ad9361 signal source?

I don’t understand what you guys do with the Fir filter found in src/core/receiver/gnss_flograph.cc

**Comment by carlesfernandez** [comment]
Hi @noelpedro 

yes, we do that in order to reduce the FFT length. The nice thing is that you can do that in the acquisition stage without losing performance in the detection.

**Comment by noelpedro** [comment]
Buenos dias Carles,

Thanks for the reply.

So the down sampling is done in the hardware correct?

Is the FIR filter in gnss_flowgraph for file signal source to the hardware accelerators?


Im current attempting to downsample the data from the AD9361 using ADI's util_fir_decimator. Having trouble with the clocking though.
