### ISSUE TITLE
Suggestion for loading of local code for tracking in FPGA

### ISSUE THREAD

**Issue by noelpedro** [gnss-sdr/gnss-sdr#401]
For the file: 

https://github.com/gnss-sdr/gnss-sdr/blob/master/src/algorithms/tracking/adapters/gps_l1_ca_dll_pll_tracking_fpga.cc

Hi all I had a suggestion on the way the PRN code is loaded into memory in tracking. Notice that tmp_value is a 32 bit integer that is either 1 or 0.
Is it possible to glue the 1 and 0s into a 32 bit word?

Example:

code = -1,-1,-1,-1,1,1,1,1,1,...

tmp_value = 000011111,...

Of course the hardware will have to account for that and the endianness when it does the FFT, but maybe its less BRAM utilization.  And also your PRN code space complexity on ARM will be reduced by a factor of 32 for each PRN.
```
for (uint32_t PRN = 1; PRN <= NUM_PRNs; PRN++)
        {
            gps_l1_ca_code_gen_int(gsl::span<int32_t>(&d_ca_codes[static_cast<int32_t>(GPS_L1_CA_CODE_LENGTH_CHIPS) * (PRN - 1)], &d_ca_codes[static_cast<int32_t>(GPS_L1_CA_CODE_LENGTH_CHIPS) * (PRN)]), PRN, 0);

            // The code is generated as a series of 1s and -1s. In order to store the values using only one bit, a -1 is stored as a 0 in the FPGA
            for (uint32_t k = 0; k < GPS_L1_CA_CODE_LENGTH_CHIPS; k++)
                {
                    int32_t tmp_value = d_ca_codes[(int32_t(GPS_L1_CA_CODE_LENGTH_CHIPS)) * (PRN - 1) + k];
                    if (tmp_value < 0)
                        {
                            tmp_value = 0;
                        }
                    tmp_value = tmp_value | LOCAL_CODE_FPGA_ENABLE_WRITE_MEMORY;
                    d_ca_codes[(int32_t(GPS_L1_CA_CODE_LENGTH_CHIPS)) * (PRN - 1) + k] = tmp_value;
                }
        }
```

**Comment by mmajoral** [comment]
You are right, this is an improvement we are planning to do.
Thanks & Regards !
Marc
