### ISSUE TITLE
Where is the log informatino for “DLOG(INFO)”？

### ISSUE THREAD

**Issue by air-elephant** [gnss-sdr/gnss-sdr#408]
If I specified the log-file path by "--log_dir=<...>", then I could see the “gnss-sdr.INFO” in that path, which seemed to be written into some log infomation by the codes "LOG(INFO)<<...".

But I couldn't find the information by the “DLOG(INFO)”, how could I get that information?

PS:
I also ran the gnss-sdr in the Qt-creator in debug mode, still didn't find DLOG(INFO) information.

**Comment by acebrianjuan** [comment]
Hi @air-elephant,

The `DLOG()` macro is defined in the `glog/logging.h` header file, which GNSS-SDR includes as a dependency.

In the following link you can see the contents of the `logging.h` file:
https://www.apt-browse.org/browse/ubuntu/bionic/universe/amd64/libgoogle-glog-dev/0.3.5-1/file/usr/include/glog/logging.h

If you take a look at **line 987**, you will find the definition of the `DLOG()` macro.

```
// Plus some debug-logging macros that get compiled to nothing for production

#if DCHECK_IS_ON()

#define DLOG(severity) LOG(severity)
```

Notice the comment above stating that said debug-logging macros _get compiled to nothing for production_. In other words, the `DLOG()` macro does nothing when building GNSS-SDR in _Release_ mode.

Try building the receiver in _Debug_ mode and see if the internal debug information is present in the log files.
To do so, pass the following flag to cmake:

```
$ cmake -DCMAKE_BUILD_TYPE=Debug ..
```

You can find more information about the available cmake flags in the documentation page:
https://gnss-sdr.org/docs/tutorials/configuration-options-building-time/

Regards,
Álvaro
