### ISSUE TITLE
telemetry dump format

### ISSUE THREAD

**Issue by ghmile** [gnss-sdr/gnss-sdr#412]
Hello, 

I am trying to create an INAV message, which can be recognized by this receiver. Thus i tried to decode a galileo E1 signal, to extract the message and use it. Someone could help me with the parameter "dump" which saves some telemetry parameters, could it help me to extract the INAV ?  

I would like to know too the format of the binary files saved by the dump option. 

If the dump can't help me can i print a variable to print the INAV message in the application file source ?
Many thanks in advance for your help

**Comment by fgallardo** [comment]
You may want to see this:
https://github.com/gnss-sdr/gnss-sdr/issues/470
