### ISSUE TITLE
BUS error

### ISSUE THREAD

**Issue by matteocutugno** [gnss-sdr/gnss-sdr#424]
Dear community,

I have a problem in real-time acquisition. I tried my first position fix and everything works well.
I'm using GNSS-SDR v0.0.13.git-next-6fcae1a91 on ubuntu 18.04.5
When I launch GNSS-SDR with RTLSDR dongle it reports me the following error.

matteo@matteo-VivoBook:~/Scrivania/rtl_sdr$ gnss-sdr -c=./rtlsdr_L1.conf
linux; GNU C++ version 7.3.0; Boost_106501; UHD_003.010.003.000-0-unknown
Initializing GNSS-SDR v0.0.13.git-next-6fcae1a91 ... Please wait.
gr-osmosdr 0.1.5 (0.1.5) gnuradio 3.8.2.0
built-in source types: file fcd rtl rtl_tcp uhd bladerf rfspace soapy redpitaya 
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Errore di bus

I have builded from source and  the only warning when I launch make command is that there could be a conflict between two version of libgnuradio, in particular 3.7.11 and 3.8.2

I tried two different front ends but the terminal reports the same bus error.
rtlsdr_test and rtlsdr programs work with rtl dongle.
Alse bladeRF command line interface works with no problems.

Thanks for any help.

Matteo

**Comment by shuwang1** [comment]
@matteocutugno, 

May I ask what is the reason for the error?

Thx!
