### ISSUE TITLE
itemsize mismatch: source_impl0:0 using 8, interleaved_short_to_complex0:0 using 2

### ISSUE THREAD

**Issue by Hermite123456** [gnss-sdr/gnss-sdr#426]
tipet@tipet-VirtualBox:~/gnss-sdr/conf$ gnss-sdr --config_file=./my_gnss-sdr.conf
Initializing GNSS-SDR v0.0.13.git-next-3daa9259e ... Please wait.
Logging will be written at "/tmp"
Use gnss-sdr --log_dir=/path/to/log to change that.
OsmoSdr arguments: rtl,bias=1
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.8.1.0
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Exact sample rate is: 2000000.052982 Hz
[R82XX] PLL not locked!
Actual RX Rate: 2e+06 [SPS]...
Actual RX Freq: 1.57542e+09 [Hz]...
PLL Frequency tune error: 0 [Hz]...
AGC enabled
Actual Bandwidth: 0 [Hz]...
Starting a TCP/IP server of RTCM messages on port 2101
The TCP/IP server of RTCM messages is up and running. Accepting connections ...
**E0918 22:08:28.809206 27321 gnss_flowgraph.cc:294] itemsize mismatch: source_impl0:0 using 8, interleaved_short_to_complex0:0 using 2**
E0918 22:08:28.809546 27321 control_thread.cc:306] Unable to connect flowgraph
Stopping TCP/IP server on port 2101
Total GNSS-SDR run time: 0.150251 [seconds]
GNSS-SDR program ended.
tipet@tipet-VirtualBox:~/gnss-sdr/conf$

**Comment by liumin-c** [comment]
Have you solved this problem? How is it solved?
