### ISSUE TITLE
Problems whit the cmak at the building moment

### ISSUE THREAD

**Issue by CastilloDelacroix** [gnss-sdr/gnss-sdr#445]
Hi, I have problems to compile and build from de source. I follow the step from the https://gnss-sdr.org/build-and-install/#build  :
$ git clone https://github.com/gnss-sdr/gnss-sdr
$ cd gnss-sdr/build
$ git checkout next
$ cmake -DENABLE_OSMOSDR=ON -DENABLE_FPGA=ON -DENABLE_PROFILING=ON DENABLE_SYSTEM_TESTING_EXTRA=ON ..
$ make

but at this step, I have problems and the console out is:

~/gnss-sdr/build$ make
[  2%] Built target volk_gnsssdr_module
[ 50%] Built target core_libs_supl
[ 53%] Built target core_system_parameters
[ 56%] Built target algorithms_libs
[ 56%] Built target acquisition_libs
[ 59%] Built target algorithms_libs_rtklib
[ 61%] Built target pvt_libs
[ 63%] Built target core_libs
[ 64%] Built target channel_libs
[ 66%] Built target acquisition_gr_blocks
[ 67%] Built target gnss_sdr_flags
[ 70%] Built target acquisition_adapters
[ 70%] Built target channel_adapters
[ 70%] Built target conditioner_adapters
[ 70%] Built target data_type_gr_blocks
[ 71%] Built target data_type_adapters
[ 71%] Built target observables_libs
[ 71%] Built target obs_gr_blocks
[ 71%] Built target obs_adapters
[ 71%] Built target telemetry_decoder_libs
[ 72%] Built target telemetry_decoder_libswiftcnav
[ 74%] Built target telemetry_decoder_gr_blocks
[ 75%] Built target telemetry_decoder_adapters
[ 76%] Built target resampler_gr_blocks
[ 76%] Built target resampler_adapters
[ 76%] Built target signal_generator_gr_blocks
[ 77%] Built target signal_generator_adapters
[ 78%] Built target signal_source_libs
[ 79%] Built target signal_source_gr_blocks
[ 81%] Built target signal_source_adapters
[ 81%] Built target input_filter_gr_blocks
[ 82%] Built target input_filter_adapters
[ 84%] Built target tracking_libs
[ 86%] Built target tracking_gr_blocks
[ 89%] Built target tracking_adapters
[ 89%] Built target pvt_gr_blocks
[ 90%] Built target pvt_adapters
[ 91%] Built target core_monitor
[ 92%] Built target core_receiver
[ 92%] Linking CXX executable gnss-sdr
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libvolk.so: undefined reference to symbol 'orc_executor_get_accumulator'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/liborc-0.4.so: error al añadir símbolos: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/main/CMakeFiles/gnss-sdr.dir/build.make:172: src/main/gnss-sdr] Error 1
make[1]: *** [CMakeFiles/Makefile2:2614: src/main/CMakeFiles/gnss-sdr.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

I really need help.

Thank you.

**Comment by carlesfernandez** [comment]
Thanks for raising this issue. Now it should be fixed in the `next` branch.
