### ISSUE TITLE
Bit boundaries detection

### ISSUE THREAD

**Issue by kewei** [gnss-sdr/gnss-sdr#446]
Hello,
I have a problem about one function of the program, where do you implement bit boundaries check or bit synchronization, for instance for GPS C/A signals. I am sorry that I didn't find it.

Thanks.
Kewei

**Comment by ZiglioUK** [comment]
For bit synchronisation you can look for example in [dll_pll_veml_tracking.cc](https://github.com/gnss-sdr/gnss-sdr/blob/master/src/algorithms/tracking/gnuradio_blocks/dll_pll_veml_tracking.cc) line 1777, where it says "Search a bit transition by sign change"
