### ISSUE TITLE
gnss_sdr_pvt.nmea

### ISSUE THREAD

**Issue by sv1** [gnss-sdr/gnss-sdr#45]
The GPRMC sentence has a little bug. The Latitude should be 3801.4808

$GPRMC,203857.000,A,381.4808,N,02350.6841,E,0.00,0.00,280317,,*36

**Comment by carlesfernandez** [comment]
Thanks for pointing this out.

Fixed in the `next` branch (commit 58e92343c74857f6908e58e1e77f04fd97842a9d)
