### ISSUE TITLE
set "SignalSource.implementation=UHD_Signal_Source" but log says it still use default File_Signal_Source

### ISSUE THREAD

**Issue by EXing** [gnss-sdr/gnss-sdr#46]
I build gnss-sdr  from source, with uhd and gnuradio build from source. 
I'm using gnss-sdr with my USRPN210 following http://gnss-sdr.org/conf/ .
What's wrong?

**Comment by EXing** [comment]
all is latest.

**Comment by EXing** [comment]
after I change default_implementation = "File_Signal_Source" into default_implementation = "UHD_Signal_Source" , it connects to my USRP device with the error: subdevice unspecified. 
I'm sure I have specified the subdevice to A:0.(I also tried B:0)
is there something wrong with parameter reader?

**Comment by EXing** [comment]
@carlesfernandez can anyone help? Thanks!

**Comment by carlesfernandez** [comment]
Please apologize our huge lag. Is this still an issue?
