### ISSUE TITLE
How we can link the external C++ signal processing library (Sigpack) to GNSS-SDR.

### ISSUE THREAD

**Issue by dinesh0612** [gnss-sdr/gnss-sdr#461]
Respected Sir,

I want to calculate the power spectral density of a signal in the GNSS-SDR C++ Code. To do the same I want to use the existing openly available C++ signal processing library functions i.e. sigpack library function (pwelch). 

I am not able to use sigpack library functions after extracting it to the local install directory i.e. after following the steps which are given on the website - http://sigpack.sourceforge.net/index.html

Here, I want to know the correct procedure to link the external C++ library i.e. Sigpack library to GNSS-SDR C++ code. 

I am getting some error - Image for the same, I have attached here

![Errorterminal](https://user-images.githubusercontent.com/32581863/104272611-8617e180-54c3-11eb-986e-53da0f0963d6.png)

Thank You

**Comment by crolen** [comment]
Can you please provide the `kaltest.cpp` file and your build script, difficult to help you without it.
