### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by songhuawang** [gnss-sdr/gnss-sdr#48]
how to install and build on windows? can you give a  instruction

**Comment by carlesfernandez** [comment]
I would say that the easiest way to install gnss-sdr on Windows is just to install a Virtual Machine with the newest Ubuntu version and then to follow the instructions for Linux machines.

You can try https://www.virtualbox.org/ It's free and works well.

[This tutorial](http://www.wikihow.com/Install-Ubuntu-on-VirtualBox) shows how to install Ubuntu with VirtualBox step by step. I hope you find it useful.

I'm closing this issue, please feel free to open a new one with a more specific question.
