### ISSUE TITLE
Check for fortran is not needed.

### ISSUE THREAD

**Issue by anthony-arnold** [gnss-sdr/gnss-sdr#5]
As far as I can tell, there's no actual fortran code in this project, and the check for gfortran is there because of the requirement for LAPACK, BLAS and Armadillo. 

I'm currently working on a buildroot configuration to install gnss-sdr on embedded devices. Fortran has been deprecated in buildroot, and the LAPACK and BLAS packages have been replaced by their C equivalents. Additionally, Armadilo can be built without a fortran compiler.

I propose that simply checking for LAPACK and BLAS is enough, and there's no need to check for fortran. This would allow configurations where non-fortran versions of LAPACK and BLAS are used.

**Comment by carlesfernandez** [comment]
Fixed. Now gfortran is not required.
