### ISSUE TITLE
Bias-tee not supported by device

### ISSUE THREAD

**Issue by fdgm0001** [gnss-sdr/gnss-sdr#505]
Hi all.

I am using bladeRF x40 and GNSS-SDR to obtain a GPS position. However, when I run the configuration file, problem with the biastee apperas, What can I do to solve it?

> Initializing GNSS-SDR v0.0.14.git-next-49fc117ab1 ... Please wait.
Logging will be written at "/tmp"
Use gnss-sdr --log_dir=/path/to/log to change that.
OsmoSdr arguments: bladerf,biastee=rx
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.9.0.0
built-in source types: file rtl rtl_tcp uhd hackrf bladerf rfspace airspy airspyhf soapy redpitaya 
[bladeRF common] init: DEBUG: entering initialization
[bladeRF source] init: Opening Nuand bladeRF with device identifier string ''
[bladeRF source] Device: Nuand bladeRF Serial # 7357...7fb6 FW v2.4.0 FPGA v0.11.0
[bladeRF source] init: Buffers: 512, samples per buffer: 4096, active transfers: 32
**[ERROR @ host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c:2918] bladerf_set_bias_tee: Board type "bladerf1" not supported
[bladeRF source] set_biastee_mode: Bias-tee not supported by device**
[bladeRF source] bladerf_source_c: DEBUG: initialization complete
Actual RX Rate: 2e+06 [SPS]...
Actual RX Freq: 1.57542e+09 [Hz]...
PLL Frequency tune error: 0 [Hz]...
[WARNING @ host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c:1869] bladerf1_get_gain_stage: gain stage 'LNA' invalid
Actual LNA Gain: 0 dB...
[WARNING @ host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c:1869] bladerf1_get_gain_stage: gain stage 'VGA1' invalid
Actual VGA1 Gain: 0 dB...
[WARNING @ host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c:1869] bladerf1_get_gain_stage: gain stage 'VGA2' invalid
Actual VGA2 Gain: 0 dB...
Actual Bandwidth: 2.8e+07 [Hz]...
RF Channels: 1
[bladeRF source] start: DEBUG: starting source

>

**Comment by AgileEngineeringLLC** [comment]
I've also had challenges with bladeRF bias tee.
A couple of other options you might consider:
1. Buy a separate biastee (GPIO Labs has some nice ones). I usually do this.
2. Set up the biastee via bladeRF-cli prior to running GNSS-SDR.
