### ISSUE TITLE
Getting 4 Valid Observables, but Error in Position please help

### ISSUE THREAD

**Issue by noelpedro** [gnss-sdr/gnss-sdr#528]
Getting this error on my LOG file: point pos err();
ANy insight on this @carlesfernandez @Arribas ?

Called from https://github.com/gnss-sdr/gnss-sdr/blob/main/src/algorithms/PVT/gnuradio_blocks/rtklib_pvt_gs.cc 

`if (d_internal_pvt_solver->get_PVT(d_gnss_observables_map, false))`

https://github.com/gnss-sdr/gnss-sdr/blob/main/src/algorithms/PVT/libs/rtklib_solver.cc

`result = rtkpos(&rtk_, obs_data.data(), valid_obs + glo_valid_obs, &nav_data);`

https://github.com/gnss-sdr/gnss-sdr/blob/main/src/algorithms/libs/rtklib/rtklib_rtkpos.cc

`if (!pntpos(obs, nu, nav, &rtk->opt, &rtk->sol, nullptr, rtk->ssat, msg))`
        `{`
           ` errmsg(rtk, "point pos error (%s)\n", msg);`
            `if (!rtk->opt.dynamics)`
             `   {`
                   ` outsolstat(rtk);`
                    `return 0;`
                `}`
        `}`

`;######### PVT CONFIG ############`
`PVT.implementation=RTKLIB_PVT`
`PVT.positioning_mode=Single`
`PVT.iono_model=OFF`
`PVT.trop_model=OFF`
`PVT.raim_fde=1`
`PVT.output_rate_ms=20;`
`PVT.display_rate_ms=500;`
`PVT.elevation_mask=0;`
`PVT.flag_rtcm_server=false`
`PVT.flag_rtcm_tty_port=false`
`PVT.rtcm_dump_devname=/dev/pts/1`
`PVT.dump=false`
`PVT.dump_filename=./PVT`

Only thing evident in LOG file is that system clock it not on UTC and pvt error time stamp is on UTC maybe thats my issue?

`#######  SOME OUTPUT FROM LOG FILE ##################`

`I0715 18:54:45.064851 11126 dll_pll_veml_tracking_fpga.cc:2256] GPS L1 C/A tracking bit synchronization locked in channel 2 for satellite GPS PRN 21 (Block IIR)`
`I0715 18:55:28.405014 11135 rtklib_solver.cc:907] RTKLIB rtkpos error: 01:54:42.66: point pos error ()`
`I0715 18:55:28.428786 11135 rtklib_solver.cc:907] RTKLIB rtkpos error: 01:54:42.68: point pos error ()`
`I0715 18:55:28.452778 11135 rtklib_solver.cc:907] RTKLIB rtkpos error: 01:54:42.70: point pos error ()`
`I0715 18:55:28.470021 11135 rtklib_solver.cc:907] RTKLIB rtkpos error: 01:54:42.72: point pos error ()`
`I0715 18:55:28.492781 11135 rtklib_solver.cc:907] RTKLIB rtkpos error: 01:54:42.74: point pos error ()`
`I0715 18:55:28.508777 11135 rtklib_solver.cc:907] RTKLIB rtkpos error: 01:54:42.76: point pos error ()`
`I0715 18:55:28.532781 11135 rtklib_solver.cc:907] RTKLIB rtkpos error: 01:54:42.78: point pos error ()`
`I0715 18:55:28.546456 11135 rtklib_solver.cc:907] RTKLIB rtkpos error: 01:54:42.80: point pos error ()`

**Comment by carlesfernandez** [comment]
Try deactivating the RAIM algorithm, i.e., `PVT.raim_fde=0`.

**Comment by noelpedro** [comment]
@carlesfernandez i believe I’ve tried that.

but I’ll double check. I was using the PVT configs from this .conf file https://github.com/gnss-sdr/gnss-sdr/blob/next/conf/gnss-sdr_GPS_L1_FPGA.conf

**Comment by noelpedro** [comment]
@carlesfernandez Is there a reason the PVT is attempted to be computed after only 3 Pages and not after the 5? The error above is happening after only the 3rd page.

**Comment by noelpedro** [comment]
estpos() is returning zero

**Comment by noelpedro** [comment]
Line 665 in https://github.com/gnss-sdr/gnss-sdr/blob/main/src/algorithms/libs/rtklib/rtklib_pntpos.cc


 `if (norm_rtk(dx, NX) < 1e-4)` is Not true

**Comment by noelpedro** [comment]
SHould the above error cause the tracking correlators to lose lock? For some reason shortly after seeing this error I lose lock of all 4 satellites.

**Comment by noelpedro** [comment]
In `rescode()` in `rtklib_pntpos.cc`

`Elaux < opt->elmin` 

causing loop to continue and thus not updating `nv` 


I have elevation mask set to 0 can i make it negative?

**Comment by noelpedro** [comment]
@carlesfernandez  I'm getting different TOW [ms] for all channels can this be the reason for failure in RTK? is there a config to allow for greater seperation in TOW when computing position?

**Comment by noelpedro** [comment]
ALso my pseudoranges are very different. Some positive other negative.

**Comment by noelpedro** [comment]
My tracking correlators respective sample counts were not synchronized with each other nor with that of the observables sample counter. I have fixed the issue and able to get PVT.

**Comment by bqui** [comment]
How were you able to the synchronization issue?  I am seeing the same problem.

**Comment by noelpedro** [comment]
All sample counters must the same.

observables sample counter with those of the multi correlators.

**Comment by Rafaykhan12** [comment]
@noelpedro can yo please explain how you solve this issue? I have also mailed you . I am getting the same problem as yours although I am running v17
