### ISSUE TITLE
What Causes the Increase in Sample Counter from Tracking Start?

### ISSUE THREAD

**Issue by jmtobin-uh** [gnss-sdr/gnss-sdr#529]
When using GNSS-SDR there always seems to be an increase in the sample counter at some point during tracking. Here is the output of PRN_start_sample_counter from the tracking dump using the "my first position fix" data.
![image](https://user-images.githubusercontent.com/71855117/126009212-12598411-cf82-4cbf-ac06-74a9c6c1772b.png)

What causes the sharp change in sample count at the elbow of the plot? Thanks!

**Comment by noelpedro** [comment]
There may exists a downsampler before acquisition and thus number of samples are shorter ( or the sample count is a lot less). The data code length might be greater for Tracking.

For example if sample rate is 4msps and Acquisition is done at 1msps. The sample count for ACQ is a a fourth less than the tracker's sample count.

**Comment by jmtobin-uh** [comment]
It seems to be that the system is sampling at 1kHz and that elbow is when it drops down to 50Hz. I suppose my question becomes what causes the change in sampling frequency?

**Comment by noelpedro** [comment]
Save some computational resources in Acquisition (i.e. reduce size of data vector of FFTs).

**Comment by jmtobin-uh** [comment]
Sure, but why not 50 Hz for the entirety then? Why begin with 1kHz?

**Comment by noelpedro** [comment]
Sample counter get uploaded by 50Hz or 20ms after bit synchronization.

**Comment by jmtobin-uh** [comment]
Do you know where that cahnge is in the source code? I can't seem to find it.

**Comment by noelpedro** [comment]
Should be at the bottom of the respective trackings’s general_work function.

**Comment by noelpedro** [comment]
Actually look at where the log_data() occurs in case 2 and case 4 of tracking loop.

case 2 logs every ms while case4 logs every 20ms.
