### ISSUE TITLE
Configuration for GPS+SBAS

### ISSUE THREAD

**Issue by a-tacky-lizard** [gnss-sdr/gnss-sdr#56]
I am trying to use both GPS and SBAS satellites. I have tried using the previous conf files (v5/6 has an SBAS conf) as references but I have been unable to successfully track both constellations with the Spain data set. 

Through my testing I have noticed that I can only seem to use 1 Telemetry block. I have put an output statement in the init function for the SBAS telemetry and it only prints whenever I set the TelDec_1C.implementation=SBAS...

If I attempt to set TelDec#=SBAS... it never gets initialized. 

Is there a working configuration file example for the newest version? master or next will do.

**Comment by carlesfernandez** [comment]
The SBAS implementation is an ongoing work, it's still not ready.
