### ISSUE TITLE
Why doesn't the configuration file contain IF frequency?

### ISSUE THREAD

**Issue by dengxu3** [gnss-sdr/gnss-sdr#570]
As I know, IF frequency is needed when searching the carrier frequency on the acquisition phase. How do the programs of acquisition operate without IF frequency provided?

**Comment by ZiglioUK** [comment]
That's what the [Frequency Translating Filter](https://gnss-sdr.org/docs/sp-blocks/input-filter/#implementation-freq_xlating_fir_filter)  does:
`InputFilter.IF=2000000`
