### ISSUE TITLE
gnss-sdr.org domain died

### ISSUE THREAD

**Issue by minecraft2048** [gnss-sdr/gnss-sdr#589]
I can't access https://gnss-sdr.org/docs/ anymore, it said that the domain has expired and give me ads instead
![image](https://user-images.githubusercontent.com/2445636/157803325-e9623e0b-393f-457b-9960-6231fe941bcb.png)

**Comment by mustafaefecetin** [comment]
Problem has solved

**Comment by carlesfernandez** [comment]
Thanks for the heads-up! Now it should be fixed.

**Comment by minecraft2048** [comment]
the website is back up again, closing this
