### ISSUE TITLE
Using Portable Binaries

### ISSUE THREAD

**Issue by SpaceJacket19** [gnss-sdr/gnss-sdr#598]
Hello I'm relatively new to gnss-sdr and this type of work in general so I'm hoping someone can help me out. I'm trying to get gnss-sdr installed onto an embedded linux machine (a beaglebone black) and the best way to go about that seems to be using a portable binary package. I've gone through the steps on the github page on how to install a portable binary and I do this using my MacBook and then I transfer the created gnss-sdr file onto the beaglebone using a microSD card. However, that is as far as I get. I don't know how to then execute the program on the embedded device or how to check if it is even installed correctly.

I may be oversimplifying this process but my troubleshooting so far hasn't yielded much. Does anyone have experience with this type of issue and any advice?

**Comment by carlesfernandez** [comment]
You can test if gnss-sdr is alive with:

```
$ gnss-sdr --version
```

But I guess this is not working. I don't know how you have built the binary, but if you are referring to the `DENABLE_GENERIC_ARCH` building option, that "generic" means it is portable among machines with the same architecture that the building host (but maybe different SIMD instruction sets), but not in different processor architectures. You just cannot compile a binary on a Mac and make it run on a Beaglebone. You will need to cross-compile the binary for the Beaglebone architecture in the appropriate environment.

Cross-compiling is always hard. We have some tools to support that, for instance https://github.com/carlesfernandez/yocto-geniux 

Clone that repo, cd on it, read the instructions (you will need Docker installed), and type:

```
./geniux-builder.sh dunfell latest beaglebone
```

This should create a `.wic` image ready to be burnt in your microSD, an SDK environment that you can use for cross-compiling, and even a docker image that can run in your Beaglebone. However, this has **not** been tested and those cross-compilation tools can be problematic when you go off-roads. Warning: this process requires a lot of free hard disk (about 50 GB) and RAM memory (at least 16 GB), and it will take several hours.

However, I guess the Beaglebone is not able to sustain real-time. For a reference, a Raspberry Pi 4 is able to sustain from 6 to 8 GPS channels with ®a basic configuration in real-time, which is not much.
