### ISSUE TITLE
Invalid preamble???

### ISSUE THREAD

**Issue by Imtiaz08** [gnss-sdr/gnss-sdr#622]
Hi everyone, 

I am trying to decode a signal recorded in a bin file using the MATLAB script. However, whenever I try to run the code it says invalid preamble. 

Below are the settings
![sett](https://user-images.githubusercontent.com/59028834/174268561-6ddedf78-1e3c-4361-9fbf-31765bf4d851.PNG)
![res](https://user-images.githubusercontent.com/59028834/174268591-fbe55045-9078-41d2-83ba-fae54832cfaa.PNG)

**Comment by carlesfernandez** [comment]
That MATLAB script does not belong to GNSS-SDR. Can't help you with that.
