### ISSUE TITLE
Wrong comment in gnss-sdr_GPS_L1_rtlsdr_realtime.conf

### ISSUE THREAD

**Issue by wkazubski** [gnss-sdr/gnss-sdr#645]
The comment in the sction SIGNAL_SOURCE CONFIG of gnss-sdr_GPS_L1_rtlsdr_realtime.conf file says:
```
; FOR USE GNSS-SDR WITH RTLSDR DONGLES USER MUST SET THE CALIBRATED SAMPLE RATE HERE
; i.e. using front-end-cal as reported here: https://www.researchgate.net/publication/257137427_Turning_a_Television_into_a_GNSS_Receiver
SignalSource.sampling_frequency=2000000
```
but in this particular place the NOMINAL sampling frequency should be set (allways 2000000, independent of xtat error).
The comment is the same as in GLOBAL OPTIONS and INPUT_FILTER CONFIG sections but the correct value of sampling frequency is different.

**Comment by carlesfernandez** [comment]
`SignalSource.sampling_frequency` should be set to the effective sampling frequency of the front-end, which includes the sampling frequency error.
