### ISSUE TITLE
On the RINEX output when tracking two channels

### ISSUE THREAD

**Issue by fgallardo** [gnss-sdr/gnss-sdr#648]
Hi all,

So, I am trying to process two files, one in E1 and another in E5. Same sampling frequency. I am using version 0.0.17.git-next-6ec452a7c
 . (By the way, thanks for the Docker images, Carles!).

Now, I can get PVT and Observation RINEX when processing individually the signal for E1 (the first file) or the second file (which contains signal E5 signals). But can I get both observations in the RINEX of both E1 and E5 when running a multichannel config? I run it and, based on the RINEX header, it seems like it wants to output both, but it does not contain the data of the E5 observables.

In theory, I should have all these measurements:

E    8 C1B L1B D1B S1B C5X L5X D5X S5X

But in all the output file, the columns I can see are those of E1 (channel 1, file 1): Code, phase, Doppler and signal strength for E1.

E02  33805967.401 7 177651552.200 7      3264.851 7        45.713               

I reckon the problem may be with my config file for multiple input files. It seems to work, as I get the output and the PVT and some data from E5 channel, but I don't find the E5 observables in the RINEX.

The doubt I have is whether I have a problem with my config or maybe it is a limitation of version 0.0.17.git-next-6ec452a7c of gnss-sdr.

For me, it is not a killer, as by looking at how the multichannel part works[1], I think I can just get the observations, input file per input file and then combine both frequencies observables (so run gnss-sdr twice, one for E1 and another one for E5), but I wanted to check.

[1] https://gnss-sdr.org/docs/sp-blocks/signal-source/#multiple-sources
https://gnss-sdr.org/assets/images/multichannel.png

**Comment by carlesfernandez** [comment]
The annotations of E5 in the RINEX files requires the full recovery of the navigation data (either I/NAV or F/NAV), so this could be the cause of not getting them.
