### ISSUE TITLE
Divide data by subframe

### ISSUE THREAD

**Issue by FayeWong98** [gnss-sdr/gnss-sdr#669]
Hello, after collecting navigation satellite data and saving it in mat format, I can see many parameters and data in matlab, such as abs_ E. L, P, PromptI, Q, etc., but this is data composed of many frames.

I want to know how to divide the data under a certain parameter into frames or subframes?

Look forward to your reply, thank you!

**Comment by carlesfernandez** [comment]
You can use the time index for each measure and group them as you wish.
