### ISSUE TITLE
Empty Rinex files

### ISSUE THREAD

**Issue by cipriancircu** [gnss-sdr/gnss-sdr#678]
Hello everyone,

While running GNSS-SDR I noticed this weird trend: for the same configuration file, but for different inputs no data would be written in a Rinex file despite position fix being achieved. 
Has anyone observed this behavior before, and if so, how did you get the tool to work properly?
Thank you!

**Comment by carlesfernandez** [comment]
In some multi-system combinations, the generation of RINEX files starts when the first PVT fix is reached AND there are ephemeris from all systems. Could that be your case?
