### ISSUE TITLE
FPGA offloading

### ISSUE THREAD

**Issue by devmonkZA** [gnss-sdr/gnss-sdr#684]
Hello , I have been working through the code , building source , on Laptop (x86) , Raspberry Pi 3 and 4 , and a cross compiled using Yocto for ADRV9361 Zynq board, also managed to build for FPGA but I cannot find the code for the UIO driver and HDL code , I see it 
"experimental", is the code not open like the rest of the project , if not then where could I find it and how much will it cost ? 

Awesome project , Thanks for sharing , learned so much about GPS, thanks to your hard work :)

**Comment by ef-newspace** [comment]
Guess I'm on my own, came across an interesting project for anyone else going through this 

http://oscillator-imp.com/dokuwiki/doku.php?id=research
https://github.com/oscimp
https://github.com/oscimp/fpga_ip

**Comment by gpswizard** [comment]
> Hello , I have been working through the code , building source , on Laptop (x86) , Raspberry Pi 3 and 4 , and a cross compiled using Yocto for ADRV9361 Zynq board, also managed to build for FPGA but I cannot find the code for the UIO driver and HDL code , I see it "experimental", is the code not open like the rest of the project , if not then where could I find it and how much will it cost ?
> 
> Awesome project , Thanks for sharing , learned so much about GPS, thanks to your hard work :)

hello for the raspberry pi3 and 4 did you cross compile with yocto?

**Comment by carlesfernandez** [comment]
The FPGA IP cores, user manuals, and example project are commercially available at https://navposproducts.cttc.es/

**Comment by devmonkZA** [comment]
Hello Carles , This is great news thanks for the the update , I will be in contact shortly

**Comment by devmonkZA** [comment]
> > Hello , I have been working through the code , building source , on Laptop (x86) , Raspberry Pi 3 and 4 , and a cross compiled using Yocto for ADRV9361 Zynq board, also managed to build for FPGA but I cannot find the code for the UIO driver and HDL code , I see it "experimental", is the code not open like the rest of the project , if not then where could I find it and how much will it cost ?
> > Awesome project , Thanks for sharing , learned so much about GPS, thanks to your hard work :)
> 
> hello for the raspberry pi3 and 4 did you cross compile with yocto?

Hello , Sorry only saw you message now , Yes  , but you could probably use Buildroot , Bootlin has toolchains as well 
https://www.buildroot.org/docs.html
https://toolchains.bootlin.com/
