### ISSUE TITLE
Invalid item type in config file

### ISSUE THREAD

**Issue by wkazubski** [gnss-sdr/gnss-sdr#688]
The config file gnss-sdr_GPS_L1_ishort.conf still contains cshort as item type descriptor, not recognized correctly now.  It should be replaced with gr_complex to make the config file working.

I have a patch in my fix-configs branch:
https://github.com/wkazubski/gnss-sdr/commit/a6bc083176fb680652502f8973abb90728d858fc

**Comment by jwmelto** [comment]
Appears to be closed by #692 ... please close?
