### ISSUE TITLE
Support for signal metadata

### ISSUE THREAD

**Issue by minecraft2048** [gnss-sdr/gnss-sdr#704]
There's two signal metadata formats that I know of;

- Gnuradio SigMF: https://github.com/gnuradio/SigMF/blob/sigmf-v1.x/sigmf-spec.md
- ION GNSS SDR: https://github.com/IonMetadataWorkingGroup/GNSS-Metadata-Standard

It will be nice if GNSS-SDR can interpret these metadata standards and automatically set sample rate, IF frequency and data type

**Comment by carlesfernandez** [comment]
Now in the `next` branch we have an implementation for a subset of possible configurations of the ION GNSS SDR Metadata Standard. Thanks for your suggestion!
