### ISSUE TITLE
MSM7 output for E6-C

### ISSUE THREAD

**Issue by wdc-rsat** [gnss-sdr/gnss-sdr#705]
Galileo E6 support is a real hidden gem of GNSS-SDR, the E6-B HAS decoder produces good and reliable results, but what is the level of support for the E6-C signal ?
Enabling Tracking_E6.track_pilot=true reports successful E6-C live tracking, but there is no MSM7 output for E6-C. MSM7 generation code is embedded into the PVT block, but without the valid I/NAV or F/NAV ephemeris data there will be no valid PVT solution. Does it mean that the MSM7 output requires the navigation data from a second parallel E5b or E5a channel ?

**Comment by carlesfernandez** [comment]
Hi @wdc-rsat ,

yes, you need a parallel channel with I/NAV messages, so you can associate the TOH conveyed in the HAS message to the corresponding TOW. Without that association, you cannot compute pseudoranges in that band, so MSM7 messages cannot be generated.
