### ISSUE TITLE
Build issue downloading test files

### ISSUE THREAD

**Issue by jwmelto** [gnss-sdr/gnss-sdr#707]
The top level CMakeLists.txt defines several options:
- `ENABLE_UNIT_TESTING` - "Build unit tests" default: ON
- `ENABLE_UNIT_TESTING_MINIMAL` - "Build a minimal set of unit tests" default: OFF
- `ENABLE_UNIT_TESTING_EXTRA` - "Download external files and build extra unit tests" default: OFF

However, a relatively recent code re-organization of the **next** branch has removed certain unit test files from the source tree, and nearly unconditionally downloads them.

In my environment, building into a Docker image behind a corporate firewall, I get this error:
```
CMake Error at src/tests/CMakeLists.txt:486 (file):
  file DOWNLOAD HASH mismatch

    for file: [/tmp/gnss-sdr/build/thirdparty/signal_samples/GPS_L1_CA_ID_1_Fs_4Msps_2ms.dat]
      expected hash: [f12ada80a2ad1bab061262e010643529]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [35;"SSL connect error"]
```
without regard to the cause of the file download issue, it seems that files should not be downloaded at all unless `ENABLE_UNIT_TESTING_EXTRA` is enabled. Currently, the download of several files are behind this guard:

`if(NOT ENABLE_PACKAGING OR NOT ENABLE_UNIT_TESTING_MINIMAL)`

This test seems inconsistent, and unexpected. Particularly since there is an option that purports to explicitly control downloading of external files that is not honored.

**Comment by carlesfernandez** [comment]
Ooops, stupid bug. It seems that I need to take basic logic lectures again :see_no_evil:. The commit above should fix this issue, thank you for raising it!
