### ISSUE TITLE
Doppler Data

### ISSUE THREAD

**Issue by alexmealster19** [gnss-sdr/gnss-sdr#708]
Hello I am using GNSS-SDR for a science mission and was wondering if it is possible to get the doppler data during a real time position fix. The gnss-sdr-monitor program is able to display it but I'm not quite clear as to where they are getting that data from.

**Comment by carlesfernandez** [comment]
The Doppler information is generated in the Tracking channels. Maybe you can modify the source code and print them in the terminal as they are computed.


For results after processing, you can check the generated observation RINEX files.
