### ISSUE TITLE
Any idea how to record AGC data with GNSS-SDR?

### ISSUE THREAD

**Issue by Imtiaz08** [gnss-sdr/gnss-sdr#716]
Ok, so I am currently trying to process the TEXBAT file and trying to develop an anti-spoofing algorithm with the help of machine learning. I have a recorded signal i.e. ds8.bin that I want to process with GNSS SDR. Since I don't have an appropriate transmitting front-end (though I have a HACKRF one but without any TCXO) therefore, I was thinking if there's a way to feed the file directly to the GNSS sdr and get AGC data as an output directly without transmitting the signal

**Comment by carlesfernandez** [comment]
Please check https://github.com/gnss-sdr/gnss-sdr/issues/723 

Regarding the AGC data, if it is embedded in TEXBAT metadata, you have to write your own parser to extract them.
