### ISSUE TITLE
Dual HackRF GLONASS L1 + L2

### ISSUE THREAD

**Issue by fl1ckje** [gnss-sdr/gnss-sdr#726]
Hello. I tried the following guide in comments from issue: https://github.com/gnss-sdr/gnss-sdr/issues/502

5-7 minutes after launch GPS L1 + GLONASS L1 using Wilkinson's divider can provide complete navigation result using GPS L1, but not using GLONASS L1.
Tried GLONASS L1 + L2, but tracking works only for L1.
Both hackrf work fine in single band (1 signal source).
How can I solve the issue?
Can I get any plots of data between processing blocks in realtime?

**Comment by Blossom-ASL** [comment]
Hello,
Where you able to get navigation result using both L1 and L2 bands? I have tried the following configuration with two bladeRFS connected to same signal source and external clock. But I am also getting navigation data using L1 band only.

Here is the configuration:

[GNSS-SDR]

;######### GLOBAL OPTIONS ##################
GNSS-SDR.internal_fs_sps=2000000
GNSS-SDR.num_sources=2

;######### SIGNAL_SOURCE 0 CONFIG ############
SignalSource0.implementation=Osmosdr_Signal_Source
SignalSource0.item_type=gr_complex
SignalSource0.sampling_frequency=2000000
SignalSource0.freq=1575420000
;#SignalSource.osmosdr_args=bladerf,bias=1
SignalSource0.osmosdr_args=bladerf=0,biastee=rx
SignalSource0.gain=40
SignalSource0.rf_gain=40
SignalSource0.if_gain=30
;SignalSource1.rf_bw=1500000
SignalSource0.if_gain=20
SignalSource0.AGC_enabled=false
SignalSource0.samples=0
SignalSource0.repeat=false
SignalSource0.enable_throttle_control=false
SignalSource0.dump=false

;######### SIGNAL_SOURCE CONFIG 1 ############
SignalSource1.implementation=Osmosdr_Signal_Source
SignalSource1.item_type=gr_complex
SignalSource1.sampling_frequency=2000000
SignalSource1.freq=1227600000
;#SignalSource.osmosdr_args=bladerf,bias=1
SignalSource1.osmosdr_args=bladerf=1,biastee=rx
SignalSource1.gain=40
SignalSource1.rf_gain=40
SignalSource1.if_gain=30
;SignalSource1.rf_bw=1500000
SignalSource1.if_gain=20
SignalSource1.AGC_enabled=false
SignalSource1.samples=0
SignalSource1.repeat=false
SignalSource1.enable_throttle_control=false
SignalSource1.dump=false


;######### SIGNAL_CONDITIONER CONFIG ############

SignalConditioner0.implementation=Signal_Conditioner
SignalConditioner1.implementation=Signal_Conditioner

;######### DATA_TYPE_ADAPTER CONFIG ############

DataTypeAdapter0.implementation=Pass_Through
DataTypeAdapter1.implementation=Pass_Through

;######### INPUT_FILTER CONFIG ############

InputFilter0.implementation=Pass_Through
InputFilter1.implementation=Pass_Through

;######### RESAMPLER CONFIG ############

Resampler0.implementation=Pass_Through
Resampler0.item_type=gr_complex

Resampler1.implementation=Pass_Through
Resampler1.item_type=gr_complex


;######### CHANNELS GLOBAL CONFIG ############

;######### CHANNELS GLOBAL CONFIG ############
Channels_2S.count=8
Channels_1C.count=8
Channels.in_acquisition=1

Channel0.Signal_Source_ID=0
Channel0.signal=1C

Channel1.Signal_Source_ID=0
Channel1.signal=1C

Channel2.Signal_Source_ID=0
Channel2.signal=1C

Channel3.Signal_Source_ID=0
Channel3.signal=1C

Channel4.Signal_Source_ID=0
Channel4.signal=1C

Channel5.Signal_Source_ID=0
Channel5.signal=1C

Channel6.Signal_Source_ID=0
Channel6.signal=1C

Channel7.Signal_Source_ID=0
Channel7.signal=1C

Channel8.Signal_Source_ID=1
Channel8.signal=2S

Channel9.Signal_Source_ID=1
Channel9.signal=2S

Channel10.Signal_Source_ID=1
Channel10.signal=2S

Channel11.Signal_Source_ID=1
Channel11.signal=2S

Channel12.Signal_Source_ID=1
Channel12.signal=2S

Channel13.Signal_Source_ID=1
Channel13.signal=2S

Channel14.Signal_Source_ID=1
Channel14.signal=2S

Channel15.Signal_Source_ID=1
Channel15.signal=2S

;######### ACQUISITION GLOBAL CONFIG ############
Acquisition_2S.implementation=GPS_L2_M_PCPS_Acquisition
Acquisition_2S.item_type=gr_complex
Acquisition_2S.doppler_max=4500
Acquisition_2S.doppler_step=200
Acquisition_2S.use_CFAR_algorithm=false
Acquisition_2S.threshold=10
Acquisition_2S.blocking=true
Acquisition_2S.coherent_integration_time_ms=20

;######### ACQUISITION GPS CONFIG ############
Acquisition_1C.implementation=GPS_L1_CA_PCPS_Acquisition
Acquisition_1C.item_type=gr_complex
Acquisition_1C.coherent_integration_time_ms=1
Acquisition_1C.pfa=0.0015
Acquisition_1C.doppler_max=5000
Acquisition_1C.doppler_step=200
Acquisition_1C.max_dwells=6


;######### TRACKING GLOBAL CONFIG ############

Tracking_2S.implementation=GPS_L2_M_DLL_PLL_Tracking
Tracking_2S.item_type=gr_complex
Tracking_2S.pll_bw_hz=4.0;
Tracking_2S.dll_bw_hz=1;
Tracking_2S.early_late_space_chips=0.5;
Tracking_2S.dump=false
Tracking_2S.dump_filename=./data/track_ch_


;######### TRACKING GPS CONFIG ############
Tracking_1C.implementation=GPS_L1_CA_DLL_PLL_Tracking
Tracking_1C.item_type=gr_complex
Tracking_1C.extend_correlation_symbols=10
Tracking_1C.early_late_space_chips=0.5
Tracking_1C.early_late_space_narrow_chips=0.15
Tracking_1C.pll_bw_hz=50.0
Tracking_1C.dll_bw_hz=8.0
Tracking_1C.pll_bw_narrow_hz=10.0
Tracking_1C.dll_bw_narrow_hz=1.50
Tracking_1C.fll_bw_hz=10
Tracking_1C.enable_fll_pull_in=true
Tracking_1C.enable_fll_steady_state=false
Tracking_1C.dump=false
Tracking_1C.dump_filename=tracking_ch_

;######### TELEMETRY DECODER CONFIG ############

TelemetryDecoder_2S.implementation=GPS_L2C_Telemetry_Decoder


;######### TELEMETRY DECODER GPS CONFIG ############
TelemetryDecoder_1C.implementation=GPS_L1_CA_Telemetry_Decoder
TelemetryDecoder_1C.dump=false


;######### OBSERVABLES CONFIG ############

Observables.implementation=Hybrid_Observables


;######### PVT CONFIG ############

PVT.implementation=RTKLIB_PVT

PVT.positioning_mode=Single; options: Single, Static, Kinematic, PPP_Static, PPP_Kinematic
PVT.iono_model=OFF; options: OFF, Broadcast, SBAS, Iono-Free-LC, Estimate_STEC, IONEX
PVT.trop_model=OFF; options: OFF, Saastamoinen, SBAS, Estimate_ZTD, Estimate_ZTD_Grad

;#output_rate_ms: Period between two PVT outputs. Notice that the minimum period is equal to the tracking integration time [ms]
PVT.output_rate_ms=100

;#display_rate_ms: Position console print (std::out) interval [ms]. Notice that output_rate_ms<=display_rate_ms.
PVT.display_rate_ms=500

;# KML, GeoJSON, NMEA and RTCM output configuration
;#dump_filename: Log path and filename without extension. Notice that PVT will add ".dat" to the binary dump and ".kml" to GoogleEarth dump.
PVT.dump_filename=./data/access18

;#nmea_dump_filename: NMEA log path and filename
PVT.nmea_dump_filename=./gnss_sdr_pvt.nmea

;#flag_nmea_tty_port: Enable or disable the NMEA log to a serial TTY port (Can be used with real hardware or virtual one)
PVT.flag_nmea_tty_port=false

;#nmea_dump_devname: serial device descriptor for NMEA logging
PVT.nmea_dump_devname=/dev/pts/4
