### ISSUE TITLE
gnss-HPSDR project with SPF+ /SPF trasnsceiver based armature radio module

### ISSUE THREAD

**Issue by BEMNETADEFIS** [gnss-sdr/gnss-sdr#73]
view openhpsdr.org

**Comment by carlesfernandez** [comment]
Interesting project. However, it seems that the transmitter does not support GNSS frequencies https://openhpsdr.org/mercury.php

**Comment by BEMNETADEFIS** [comment]
the device design required more design selection but i have develop the
systems in to

   1. type 1
   2. type 2
   3. type 3 using commerical GNSS/GPS integrated modules and others
   devices but i need wikisdr modules and openhpsdr modules with zed board
   carrier board so what is the recommendation of the project.


best regards

bemnet adefris

open source developer
