### ISSUE TITLE
Terminating GNSS-SDR from a shell script

### ISSUE THREAD

**Issue by alexmealster19** [gnss-sdr/gnss-sdr#733]
Hi I am running GNSS-SDR in an automated environment on a linux device and I have questions on the best way to terminate the program. So for context, I have a shell script that, once the linux device is powered, will do a system checkout and if everything looks good it will begin running gnss-sdr. Currently it runs gnss-sdr via a line such as the one below
`gnss-sdr --config_file=myConfigFile.conf &`

This line will run gnss-sdr in the background so I can continue to do other tasks with my shell script. My current issue is that I'm not sure the best way to log data and safely terminate the program so that I get the most data safely stored. There are three possibilities:

1. The linux device will get a message saying to power off and I'll have a small window of time to properly shut off gnss-sdr and store data.
2. The linux device will unexpectedly lose power.
3. The linux device will recognize that there has been a successful position fix and which point it will terminate gnss-sdr and safely store the data. 

The first possibility on the list is the most important. Currently I'm using something like this:
`if pgrep -x "gnss-sdr" > /dev/null`
`then`
`    echo "GNSS-SDR is already running. Stopping GNSS-SDR." `
`    killall gnss-sdr `

but this doesn't properly save rinex files. If I was running it normally I could just input q+enter to terminate the program so a shell script version of that is what I'm looking for. 

The second possibility is less about how I terminate gnss-sdr (since power is lost randomly) and more about how I save the data originally.

The third possibility is more of a wishlist item but would be excellent to have!

I'm fairly new to writing shell scripts so it's quite possible that there are some easy solutions that I'm missing. Would appreciate any ideas anyone has!

**Comment by carlesfernandez** [comment]
The current version of GNSS-SDR supports `SIGINT`, `SIGTERM` and `SIGHUP`.
