### ISSUE TITLE
cross compiling user name and password

### ISSUE THREAD

**Issue by HomeInSnow** [gnss-sdr/gnss-sdr#745]
what's the login user name and password of the cross compiling linux root file system?  I cann't login with the root name 

zedboard-zynq7 login: root

Cannot
Geniux gatesgarth-21.08.0 zedboard-zynq7 ttyPS0

zedboard-zynq7 login: root
Last login: 
Geniux gatesgarth-21.08.0 zedboard-zynq7 ttyPS0

zedboard-zynq7 login: root
Last login: 
Geniux gatesgarth-21.08.0 zedboard-zynq7 ttyPS0
zedboard-zynq7 login:

**Comment by carlesfernandez** [comment]
By default, both the user and the password are `geniux` .
