### ISSUE TITLE
trivial documentation correction for FIFO

### ISSUE THREAD

**Issue by jmfriedt** [gnss-sdr/gnss-sdr#746]
The documentation at https://gnss-sdr.org/docs/sp-blocks/signal-source/#reading-data-from-a-pipe states that the input arguments of the FIFO are sample_type defined as [ishort, gr_complex]. As I was about to implement the 8-bit integer data stream, I realized ibyte was implemented and seems to be working well. It would be nice to add this data type to the documentation, unless there is an issue I have not hit when using it.
Thanks

**Comment by carlesfernandez** [comment]
Fixed! Thanks
