### ISSUE TITLE
The results of decoding navigation message is erro

### ISSUE THREAD

**Issue by Assely11** [gnss-sdr/gnss-sdr#751]
Yeah, now I'm observing GPS satellite in China by gnss-sdr. The acquisition block can cache 7 satellites, and the 7 satellites also can be tracked successfully. however, the navigation messages decoded by gnss-sdr are wrong. so, the trouble should how to be solved.

**Comment by carlesfernandez** [comment]
The reception of GPS navigation messages seems to work well both in unit tests and in regular usage of GNSS-SDR. 

If the issue persists, please feel free to open a new issue with more details.
