### ISSUE TITLE
Impossible to build on MAC Sonoma 14.1.1

### ISSUE THREAD

**Issue by SoniaKaudjhis** [gnss-sdr/gnss-sdr#752]
Hi I try to build gnss-sdr on Mac Sonoma 14.1.1 I have the following issue when it try to install libraries : 
Can you help me with that issue ? 
### Scenario 
` cmake -DCMAKE_INSTALL_PREFIX=/opt/local -DENABLE_OSMOSDR=ON ../`
`make -j 10`
Then 
### Error 
`[ 55%] No install step for 'protobuf-25.0'
[ 55%] Completed 'protobuf-25.0'
[ 55%] Built target protobuf-25.0`
### Investigation 
I notice also there is a missing libraries in opt/local/include/gnuradio/types
![Screenshot 2024-01-07 at 6 58 54 PM (2)](https://github.com/gnss-sdr/gnss-sdr/assets/1808514/d8bc30ea-71eb-447f-9323-e1424554dd82)
### System information 
OS : MAC Sonoma 14.1.1
Python 3.9.10
GnuRadio : 3.8.5.0

Thanks for your help.

**Comment by jwmelto** [comment]
Can you post the entire output of your build (not a screen shot)?

**Comment by SoniaKaudjhis** [comment]
Here is my build output : 
[build_ouput.txt](https://github.com/gnss-sdr/gnss-sdr/files/13855444/build_ouput.txt)

**Comment by jwmelto** [comment]
What version of GNU Radio do you have and how was it installed? The commit that replaced `boost::shared_ptr` with `std::shared_ptr` was 4 years ago.

What version of GNSS-SDR do you have? I can't find the commit hash (`v0.0.18.git-next-8e1a7ce78`) you built in the next branch.

You also have a very new version of Boost (where, apparently, they removed the file `boost/shared_ptr.hpp`).

In my (limited) experience, if you are going to build from source, you commit to building all the dependencies from source as well. This appears to be a case where your Boost is too new for your version of GNU Radio.

**Comment by jwmelto** [comment]
No, your GNU Radio is too old. https://formulae.brew.sh/formula/gnuradio says that it installs GNU Radio 3.10 (which is substantially different from 3.8).

If you want to use an older GNU Radio, you will need an older Boost.

**Comment by SoniaKaudjhis** [comment]
@jwmelto which version on GNU Radio which has acceptable for make it work ?

**Comment by SoniaKaudjhis** [comment]
@jwmelto I can build without issue. Thanks for your help

**Comment by SoniaKaudjhis** [comment]
This issue is resolved
