### ISSUE TITLE
Not saving Acq files for E5a signals

### ISSUE THREAD

**Issue by juanalfarom** [gnss-sdr/gnss-sdr#764]
Hi, I am currently working with GALILEO E5a signals and the code works great giving me the correct coordinates while executing the .conf file. The problem is that after the execution, the .mat files of the acquisition are not saved in the computer. The rest of the blocks are saved correctly. Any hint explaining this? The saving lines I am including are the following: 

Acquisition_5X.dump=true
Acquisition_5X.dump_filename=GPS_acquisition/acq_ch

**Comment by carlesfernandez** [comment]
Please make sure that ```Acquisition_5X.dump_channel``` points to a channel number where you are actually processing Galileo E5a signals.
