### ISSUE TITLE
Hardware requirements estimation/perfomance benchmarking

### ISSUE THREAD

**Issue by djObsidian** [gnss-sdr/gnss-sdr#769]
The documentation on the site does a good job of covering GNSS-SDR compatibility with different architectures and the build process. However, there is almost nothing about performance. The only mention is on RTL2832U tutorial that states
> This configuration enables the real-time receiver operation with 8 satellite channels in an Intel Core 2 quad Q9400 @ 2.66 GHz with 4 GB of RAM

This is with 8 tracking channels and 1 acquisition channel. 
I want to make a multi-system receiver for say GPS, Galileo and BeiDou on the L1 frequency, with 4 acquisition channels and 8 tracking channels for each system. What sort of processor would be needed to make this work in real time? Preferably embedded. Will a Raspberry Pi 5 be sufficient for this? Or Orange Pi 5? Or would it require a less powerful processor like the Allwinner H618?
I realize that it's hard to estimate performance this way, but I need to at least roughly choose a processor for such a task. 
Are there any benchmarks on more modern hardware than the previously mentioned Intel Core 2 quad?

**Comment by carlesfernandez** [comment]
Hi,

We understand that providing specific benchmark results for different architectures is important, but unfortunately, we are unable to offer those at this time.
