### ISSUE TITLE
front-end-cal is turning off internal bias-t of rtl-sdr.com v3

### ISSUE THREAD

**Issue by sv1** [gnss-sdr/gnss-sdr#77]
Hello I am using an RTL-SDR.com V3  which has an internal bias-t for powering my active gps antenna. The gnss apps (front-end-call, gnss-sdr) upon startup, they disable the bias-t, causing no gps signals to be found.

**Comment by carlesfernandez** [comment]
Hi,

thanks for pointing this out. At https://www.rtl-sdr.com/rtl-sdr-blog-v-3-dongles-user-guide/ I’ve found some code that activates the bias-t. I’m pasting it below for the records. Since the current version of osmosdr does not seem to implement this feature, we have some options here:
  1.  Maybe it makes sense to write a new signal source for rtl-sdr dongles, based on librtlsdr-dev (which installs /usr/include/rtl-sdr.h and the library). The rtlsdr API provides ```int rtlsdr_set_bias_tee(rtlsdr_dev_t *dev, int on);```, at least at its latest version.
  2. Ok, this is a long shot: Could you try to use the [RtlTcp_Signal_Source](http://gnss-sdr.org/docs/sp-blocks/signal-source/#implementation-rtltcp_signal_source) and call rtl_tcp with the ```-T``` flag? Example:

<pre>
$ rtl_tcp -a 127.0.0.1 -f 1575420000 -g 0 -s 2000000 <b>-T</b>
</pre>


### Just for the records
The code that actually implements the activation is:

<pre>
#include <libusb.h>
//...

enum sys_reg {
	DEMOD_CTL = 0x3000,
	<b>GPO = 0x3001,</b>
	GPI = 0x3002,
	<b>GPOE = 0x3003,</b>
	<b>GPD = 0x3004,</b>
	SYSINTE = 0x3005,
	SYSINTS = 0x3006,
	GP_CFG0 = 0x3007,
	GP_CFG1 = 0x3008,
	SYSINTE_1 = 0x3009,
	SYSINTS_1 = 0x300a,
	DEMOD_CTL_1 = 0x300b,
	IR_SUSPEND = 0x300c,
};

enum blocks {
	DEMODB = 0,
	USBB = 1,
	<b>SYSB = 2,</b>
	TUNB = 3,
	ROMB = 4,
	IRB = 5,
	IICB = 6,
};


int rtlsdr_set_bias_tee(rtlsdr_dev_t *dev, int on)
{
	if (!dev)
		return -1;

	rtlsdr_set_gpio_output(dev, 0);
	rtlsdr_set_gpio_bit(dev, 0, on);

	return 1;
}

void rtlsdr_set_gpio_output(rtlsdr_dev_t *dev, uint8_t gpio)
{
	int r;
	gpio = 1 << gpio;

	r = rtlsdr_read_reg(dev, SYSB, GPD, 1);
	rtlsdr_write_reg(dev, SYSB, GPD, r & ~gpio, 1);
	r = rtlsdr_read_reg(dev, SYSB, GPOE, 1);
	rtlsdr_write_reg(dev, SYSB, GPOE, r | gpio, 1);
}



void rtlsdr_set_gpio_bit(rtlsdr_dev_t *dev, uint8_t gpio, int val)
{
	uint16_t r;

	gpio = 1 << gpio;
	r = rtlsdr_read_reg(dev, SYSB, GPO, 1);
	r = val ? (r | gpio) : (r & ~gpio);
	rtlsdr_write_reg(dev, SYSB, GPO, r, 1);
}



uint16_t rtlsdr_read_reg(rtlsdr_dev_t *dev, uint8_t block, uint16_t addr, uint8_t len)
{
	int r;
	unsigned char data[2];
	uint16_t index = (block << 8);
	uint16_t reg;

	r = libusb_control_transfer(dev->devh, CTRL_IN, 0, addr, index, data, len, CTRL_TIMEOUT);

	if (r < 0)
		fprintf(stderr, "%s failed with %d\n", __FUNCTION__, r);

	reg = (data[1] << 8) | data[0];

	return reg;
}


int rtlsdr_write_reg(rtlsdr_dev_t *dev, uint8_t block, uint16_t addr, uint16_t val, uint8_t len)
{
	int r;
	unsigned char data[2];

	uint16_t index = (block << 8) | 0x10;

	if (len == 1)
		data[0] = val & 0xff;
	else
		data[0] = val >> 8;

	data[1] = val & 0xff;

	r = libusb_control_transfer(dev->devh, CTRL_OUT, 0, addr, index, data, len, CTRL_TIMEOUT);

	if (r < 0)
		fprintf(stderr, "%s failed with %d\n", __FUNCTION__, r);

	return r;
}
</pre>

**Comment by sv1** [comment]
Hello Charles,

the actual code for turning on the internal bias-t is here:

https://github.com/rtlsdrblog/rtl_biast

which is the one I use to turn on/off the bias-t.

In this commit:

https://github.com/osmocom/gr-osmosdr/commit/3c7d3f166401b1af6afd903b8d
2b9729e8897189


on June 11th, the bias-t is implemented in osmosdr so it is a matter of
time to hit the linux distros.


BR
Apostolos


On Tue, 2017-10-17 at 18:27 +0000, Carles Fernandez wrote:
> Hi,
> thanks for pointing this out. At https://www.rtl-sdr.com/rtl-sdr-blog
> -v-3-dongles-user-guide/ I’ve found some code that activates the
> bias-t. I’m pasting it below for the records. Since the current
> version of osmosdr does not seem to implement this feature, we have
> some options here:
> Maybe it makes sense to write a new signal source for rtl-sdr
> dongles, based on librtlsdr-dev (which installs /usr/include/rtl-
> sdr.h and the library). The rtlsdr API provides int
> rtlsdr_set_bias_tee(rtlsdr_dev_t *dev, int on);, at least at its
> latest version.
> Ok, this is a long shot: Could you try to use the
> RtlTcp_Signal_Source and call rtl_tcp with the -T flag? Example:
> $ rtl_tcp -a 127.0.0.1 -f 1575420000 -g 0 -s 2000000 -T
> Just for the records
> The code that actually implements the activation is:
> #include 
> //...
> 
> enum sys_reg {
> 	DEMOD_CTL = 0x3000,
> 	GPO = 0x3001,
> 	GPI = 0x3002,
> 	GPOE = 0x3003,
> 	GPD = 0x3004,
> 	SYSINTE = 0x3005,
> 	SYSINTS = 0x3006,
> 	GP_CFG0 = 0x3007,
> 	GP_CFG1 = 0x3008,
> 	SYSINTE_1 = 0x3009,
> 	SYSINTS_1 = 0x300a,
> 	DEMOD_CTL_1 = 0x300b,
> 	IR_SUSPEND = 0x300c,
> };
> 
> enum blocks {
> 	DEMODB = 0,
> 	USBB = 1,
> 	SYSB = 2,
> 	TUNB = 3,
> 	ROMB = 4,
> 	IRB = 5,
> 	IICB = 6,
> };
> 
> 
> int rtlsdr_set_bias_tee(rtlsdr_dev_t *dev, int on)
> {
> 	if (!dev)
> 		return -1;
> 
> 	rtlsdr_set_gpio_output(dev, 0);
> 	rtlsdr_set_gpio_bit(dev, 0, on);
> 
> 	return 1;
> }
> 
> void rtlsdr_set_gpio_output(rtlsdr_dev_t *dev, uint8_t gpio)
> {
> 	int r;
> 	gpio = 1 << gpio;
> 
> 	r = rtlsdr_read_reg(dev, SYSB, GPD, 1);
> 	rtlsdr_write_reg(dev, SYSB, GPD, r & ~gpio, 1);
> 	r = rtlsdr_read_reg(dev, SYSB, GPOE, 1);
> 	rtlsdr_write_reg(dev, SYSB, GPOE, r | gpio, 1);
> }
> 
> 
> 
> void rtlsdr_set_gpio_bit(rtlsdr_dev_t *dev, uint8_t gpio, int val)
> {
> 	uint16_t r;
> 
> 	gpio = 1 << gpio;
> 	r = rtlsdr_read_reg(dev, SYSB, GPO, 1);
> 	r = val ? (r | gpio) : (r & ~gpio);
> 	rtlsdr_write_reg(dev, SYSB, GPO, r, 1);
> }
> 
> 
> 
> uint16_t rtlsdr_read_reg(rtlsdr_dev_t *dev, uint8_t block, uint16_t
> addr, uint8_t len)
> {
> 	int r;
> 	unsigned char data[2];
> 	uint16_t index = (block << 8);
> 	uint16_t reg;
> 
> 	r = libusb_control_transfer(dev->devh, CTRL_IN, 0, addr, index,
> data, len, CTRL_TIMEOUT);
> 
> 	if (r < 0)
> 		fprintf(stderr, "%s failed with %d\n", __FUNCTION__,
> r);
> 
> 	reg = (data[1] << 8) | data[0];
> 
> 	return reg;
> }
> 
> 
> int rtlsdr_write_reg(rtlsdr_dev_t *dev, uint8_t block, uint16_t addr,
> uint16_t val, uint8_t len)
> {
> 	int r;
> 	unsigned char data[2];
> 
> 	uint16_t index = (block << 8) | 0x10;
> 
> 	if (len == 1)
> 		data[0] = val & 0xff;
> 	else
> 		data[0] = val >> 8;
> 
> 	data[1] = val & 0xff;
> 
> 	r = libusb_control_transfer(dev->devh, CTRL_OUT, 0, addr,
> index, data, len, CTRL_TIMEOUT);
> 
> 	if (r < 0)
> 		fprintf(stderr, "%s failed with %d\n", __FUNCTION__,
> r);
> 
> 	return r;
> }
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/gnss-
> sdr/gnss-sdr","title":"gnss-sdr/gnss-sdr","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/gnss-sdr/gnss-
> sdr"}},"updates":{"snippets":[{"icon":"PERSON","message":"@carlesfern
> andez in #77: Hi,\r\n\r\nthanks for pointing this out. At
> https://www.rtl-sdr.com/rtl-sdr-blog-v-3-dongles-user-guide/ I’ve
> found some code that activates the bias-t. I’m pasting it below for
> the records. Since the current version of osmosdr does not seem to
> implement this feature, we have some options here:\r\n 1. Maybe it
> makes sense to write a new signal source for rtl-sdr dongles, based
> on librtlsdr-dev (which installs /usr/include/rtl-sdr.h and the
> library). The rtlsdr API provides ```int
> rtlsdr_set_bias_tee(rtlsdr_dev_t *dev, int on);```, at least at its
> latest version.\r\n 2. Ok, this is a long shot: Could you try to use
> the [RtlTcp_Signal_Source](http://gnss-sdr.org/docs/sp-blocks/signal-
> source/#implementation-rtltcp_signal_source) and call rtl_tcp with
> the ```-T``` flag? Example:\r\n\r\n\u003cpre\u003e\r\n$ rtl_tcp -a
> 127.0.0.1 -f 1575420000 -g 0 -s 2000000 \u003cb\u003e-
> T\u003c/b\u003e\r\n\u003c/pre\u003e\r\n\r\n\r\n### Just for the
> records\r\nThe code that actually implements the activation
> is:\r\n\r\n\u003cpre\u003e\r\n#include
> \u003clibusb.h\u003e\r\n//...\r\n\r\nenum sys_reg {\r\n\tDEMOD_CTL =
> 0x3000,\r\n\t\u003cb\u003eGPO = 0x3001,\u003c/b\u003e\r\n\tGPI =
> 0x3002,\r\n\t\u003cb\u003eGPOE =
> 0x3003,\u003c/b\u003e\r\n\t\u003cb\u003eGPD =
> 0x3004,\u003c/b\u003e\r\n\tSYSINTE = 0x3005,\r\n\tSYSINTS =
> 0x3006,\r\n\tGP_CFG0 = 0x3007,\r\n\tGP_CFG1 = 0x3008,\r\n\tSYSINTE_1
> = 0x3009,\r\n\tSYSINTS_1 = 0x300a,\r\n\tDEMOD_CTL_1 =
> 0x300b,\r\n\tIR_SUSPEND = 0x300c,\r\n};\r\n\r\nenum blocks
> {\r\n\tDEMODB = 0,\r\n\tUSBB = 1,\r\n\t\u003cb\u003eSYSB =
> 2,\u003c/b\u003e\r\n\tTUNB = 3,\r\n\tROMB = 4,\r\n\tIRB =
> 5,\r\n\tIICB = 6,\r\n};\r\n\r\n\r\nint
> rtlsdr_set_bias_tee(rtlsdr_dev_t *dev, int on)\r\n{\r\n\tif
> (!dev)\r\n\t\treturn -1;\r\n\r\n\trtlsdr_set_gpio_output(dev,
> 0);\r\n\trtlsdr_set_gpio_bit(dev, 0, on);\r\n\r\n\treturn
> 1;\r\n}\r\n\r\nvoid rtlsdr_set_gpio_output(rtlsdr_dev_t *dev, uint8_t
> gpio)\r\n{\r\n\tint r;\r\n\tgpio = 1 \u003c\u003c gpio;\r\n\r\n\tr =
> rtlsdr_read_reg(dev, SYSB, GPD, 1);\r\n\trtlsdr_write_reg(dev, SYSB,
> GPD, r \u0026 ~gpio, 1);\r\n\tr = rtlsdr_read_reg(dev, SYSB, GPOE,
> 1);\r\n\trtlsdr_write_reg(dev, SYSB, GPOE, r | gpio,
> 1);\r\n}\r\n\r\n\r\n\r\nvoid rtlsdr_set_gpio_bit(rtlsdr_dev_t *dev,
> uint8_t gpio, int val)\r\n{\r\n\tuint16_t r;\r\n\r\n\tgpio = 1
> \u003c\u003c gpio;\r\n\tr = rtlsdr_read_reg(dev, SYSB, GPO,
> 1);\r\n\tr = val ? (r | gpio) : (r \u0026
> ~gpio);\r\n\trtlsdr_write_reg(dev, SYSB, GPO, r,
> 1);\r\n}\r\n\r\n\r\n\r\nuint16_t rtlsdr_read_reg(rtlsdr_dev_t *dev,
> uint8_t block, uint16_t addr, uint8_t len)\r\n{\r\n\tint
> r;\r\n\tunsigned char data[2];\r\n\tuint16_t index = (block
> \u003c\u003c 8);\r\n\tuint16_t reg;\r\n\r\n\tr =
> libusb_control_transfer(dev-\u003edevh, CTRL_IN, 0, addr, index,
> data, len, CTRL_TIMEOUT);\r\n\r\n\tif (r \u003c
> 0)\r\n\t\tfprintf(stderr, \"%s failed with %d\\n\", __FUNCTION__,
> r);\r\n\r\n\treg = (data[1] \u003c\u003c 8) |
> data[0];\r\n\r\n\treturn reg;\r\n}\r\n\r\n\r\nint
> rtlsdr_write_reg(rtlsdr_dev_t *dev, uint8_t block, uint16_t addr,
> uint16_t val, uint8_t len)\r\n{\r\n\tint r;\r\n\tunsigned char
> data[2];\r\n\r\n\tuint16_t index = (block \u003c\u003c 8) |
> 0x10;\r\n\r\n\tif (len == 1)\r\n\t\tdata[0] = val \u0026
> 0xff;\r\n\telse\r\n\t\tdata[0] = val \u003e\u003e 8;\r\n\r\n\tdata[1]
> = val \u0026 0xff;\r\n\r\n\tr = libusb_control_transfer(dev-
> \u003edevh, CTRL_OUT, 0, addr, index, data, len,
> CTRL_TIMEOUT);\r\n\r\n\tif (r \u003c 0)\r\n\t\tfprintf(stderr, \"%s
> failed with %d\\n\", __FUNCTION__, r);\r\n\r\n\treturn
> r;\r\n}\r\n\u003c/pre\u003e"}],"action":{"name":"View
> Issue","url":"https://github.com/gnss-sdr/gnss-
> sdr/issues/77#issuecomment-337322433"}}}
-- 


  
  


Κεφάλας Απόστολος -  SV1LJJ 

τηλ: +30 6979 976 039
Echolink id: 309275
skype: apostolis.kef
sip:apkefalas@iptel.org
PGP: 0xA3C19DA0

**Comment by carlesfernandez** [comment]
Oh, that's awesome. So a simple addition to Osmosdr_Signal_Source would be enough. Thanks for the pointers!

**Comment by carlesfernandez** [comment]
Looking at the code, it seems that using [Osmosdr_Signal_Source](http://gnss-sdr.org/docs/sp-blocks/signal-source/#implementation-osmosdr_signal_source) with ```SignalSource.osmosdr_args=bias=1``` would do the job.

**Comment by OrbitTheSun** [comment]
Whether the bias-tee is turned off before reception depends on which version of gr-osmosdr was used when compiling GNSS-SDR.

With an older version (for example, v0.1.4.8), the utility [rtl_bias](https://github.com/OrbitTheSun/rtl_biast) may be used to switch the bias-tee. Front-end-cal can then be called with the bias-tee turned on. Same applies to gnss-sdr. After reception the bias-tee is switched off automatically by the programs.

However with a newer version of [gr-osmosdr](https://github.com/osmocom/gr-osmosdr), i.e. the current v0.1.4-98, the bias-tee is turned off before reception, unless the `SignalSource.osmosdr_args` has been given the correct parameter. It took me a while to figure out what to do. Add the following line to the configuration files:

    SignalSource.osmosdr_args=rtl,bias=1

Without 'rtl,', the bias-tee will be turned off!

**Comment by carlesfernandez** [comment]
Awesome! Thanks for sharing.

**Comment by carlesfernandez** [comment]
Added to the documentation at http://gnss-sdr.org/docs/sp-blocks/signal-source/#implementation-osmosdr_signal_source

**Comment by OrbitTheSun** [comment]
Thank you, Carles! - Perhaps you may add the line with a short note to the file `gnss-sdr_GPS_L1_rtlsdr_realtime.conf` and to `front-end-cal.conf` commented out.

**Comment by carlesfernandez** [comment]
Done!
