### ISSUE TITLE
No telemetry decoder .mat files

### ISSUE THREAD

**Issue by jnunezortuno** [gnss-sdr/gnss-sdr#771]
I'm trying to log tne GPS L1/CA NAV message adding following lines to the conf file:

TelemetryDecoder_1C.implementation=GPS_L1_CA_Telemetry_Decoder
TelemetryDecoder_1C.dump=true
TelemetryDecoder_1C.remove_dat=false

I get a fix after 40 seconds and obtain the .dat files, but there are no .mat files.

I'm using GNSS-SDR v0.0.18.

**Comment by jwmelto** [comment]
The matlab files are generate at program shutdown, not "just in time". You probably want to record some signal that demonstrates your desired condition and do a file playback of it. The program will terminate at end of file and you will get your .mat files.

**Comment by jnunezortuno** [comment]
Yes, I am using a generated time-limited signal.

**Comment by jwmelto** [comment]
See [here](https://github.com/gnss-sdr/gnss-sdr/blob/fbc216c1a3822d248c76f07fd0ae32c730d4665d/src/algorithms/telemetry_decoder/gnuradio_blocks/gps_l1_ca_telemetry_decoder_gs.cc#L180-L190). Your program must terminate cleanly (object destructors must fire) and you need BOTH  `.dump=true` and `.dump_mat=true`

**Comment by jnunezortuno** [comment]
Added _TelemetryDecoder_1C.dump_mat=true_ but still doesn't works for me

**Comment by jnunezortuno** [comment]
Actually a message indicating .mat file creation is generated by GNSS-SDR but there is no .mat files, only .dat files.

_Position at 2024-May-06 16:08:52.500000 UTC using 6 observations is Lat = X [deg], Long = Y [deg], Height = Z [m]
Velocity: East: -0.14 [m/s], North: -0.29 [m/s], Up = 0.23 [m/s]
Current receiver time: 1 min 1 s
Stopping GNSS-SDR, please wait!
Generating .mat file for telemetry0
Generating .mat file for telemetry1
Generating .mat file for telemetry2
Generating .mat file for telemetry3
Generating .mat file for telemetry4
Generating .mat file for telemetry5
Generating .mat file for telemetry6
Generating .mat file for telemetry7
Stopping TCP/IP server on port 2101
Total GNSS-SDR run time: 35.68 [seconds]
GNSS-SDR program ended._

**Comment by jwmelto** [comment]
can you share your config and data file? I've never had issue with the .mat files before.

**Comment by jnunezortuno** [comment]
Here you have!

https://drive.google.com/file/d/1PSdKRin5Pm9v3o0d3JlSBZU5otxdm_eZ/view?usp=sharing

https://drive.google.com/file/d/1divy2HmxaPYEbRaejlWL0-A3phWOqm6p/view?usp=sharing

**Comment by carlesfernandez** [comment]
Could you please try the most recent version of GNSS-SDR? Your configuration file looks good to me.
