### ISSUE TITLE
Quation: Input Observation rinex possible?

### ISSUE THREAD

**Issue by Raviu56** [gnss-sdr/gnss-sdr#772]
I've done a lot of search and cannot find how - and if it possible at all - to use input Observation rinex file to feed gnss-sdr so as I can test post-RF system components and positioning algorithms?

So much like gnss-sdr with file_input_source of dumped signal, can I run gnss-sdr like this:
`gnss-sdr --rinex-obs-source=rinex3_log.24o`
For example, which would require rinex NAV -aka ephemeris- data file too
If you've a discord server for help or so, give the URL please.

**Comment by carlesfernandez** [comment]
Thank you for your suggestion. Unfortunately, this feature is currently not available.

**Comment by Zi7ar21** [comment]
I don't know about Discord but there is a Matrix channel: <https://matrix.to/#/#gnss-sdr:gnuradio.org>

Never seems to get much activity though.

For post-processing, [GNSS-SDR currently only has "RTKLIB_PVT"](https://gnss-sdr.org/docs/sp-blocks/pvt/#implementation-rtklib_pvt), which uses [RTKLIB](https://www.rtklib.com/) (repo at <https://github.com/tomojitakasu/RTKLIB>), which has a few GUI and CLI tools that perform the same function as the PVT stage of GNSS-SDR, except with more functionality:
```
Function                                 GUI AP         CUI AP
(a) AP Launcher                          RTKLAUNCH      -
(b) Real-Time Positioning                RTKNAVI        RTKRCV
(c) Communication Server                 STRSVR         STR2STR
(d) Post-Processing Analysis             RTKPOST        RNX2RTKP
(e) RINEX Converter                      RTKCONV        CONVBIN
(f) Plot Solutions and Observation Data  RTKPLOT        -
(g) Downloader of GNSS Data              RTKGET         -
(h) NTRIP Browser                        SRCTBLBROWS    -
```
