### ISSUE TITLE
Issue with PVT calculation in dual band (L1 / L5)

### ISSUE THREAD

**Issue by samb-devel** [gnss-sdr/gnss-sdr#775]
Dear all,

First of all, thank you so much for this fantastic software!

I have recorded two files, one centered on L1 1575.42MHz and the other centered on L5 1176.45MHz, with 24Msps IQ.
I'm using GNSS-SDR 0.0.19 from Ubuntu 24.04.

When I run the configuration file with L1CA, I get a fix quite rapidly and a PVT solution every half a second.
With L1CA and E1B, that still works well. As soon as I also enable signals from band L5 (L5 and E5A), then I can see satellites in both L1/L5 bands, including GPS L5. It fixes using L1 mostly, and then as soon as satellites in band L5 are getting used for the solution, then most of the time no PVT solutions are printed anymore, except one or two every now and then.

I disable the L5 receivers just by setting the corresponding channels to 0 instead of 10:

```
Channels_1C.count=10
Channels_1B.count=10
Channels_L5.count=0
Channels_5X.count=0
```

The configuration file is here: 
[L1_E1_L5_E5a_12Msps.txt](https://github.com/gnss-sdr/gnss-sdr/files/15500360/L1_E1_L5_E5a_12Msps.txt)

Am I doing something wrong? Is this a bug?

Thank you and kind regards,

Sam

**Comment by carlesfernandez** [comment]
I can't spot any obvious error in your configuration.

Could you try the L5/E5 alone? That is:
```
Channels_1C.count=0
Channels_1B.count=0
Channels_L5.count=10
Channels_5X.count=10
```

Please let us know if this works for you, so we can better isolate the source of the issue.
