### ISSUE TITLE
Building GNSS-SDR from source error using m3 pro MacBook Pro

### ISSUE THREAD

**Issue by xin0606** [gnss-sdr/gnss-sdr#785]
I'm currently try to build GNSS-SDR from source using M3 pro Macbook pro in Sonoma 14. I using homebrew to install all dependency with anaconda python environment.
However, the error occurs when I try to link gnss-sdr executable, the error messages are as below:

<img width="1370" alt="截圖 2024-07-05 晚上8 00 27" src="https://github.com/gnss-sdr/gnss-sdr/assets/77852099/49b1677a-4407-4d0d-87e4-30c411436cd9"> 

<img width="610" alt="截圖 2024-07-05 晚上7 59 17" src="https://github.com/gnss-sdr/gnss-sdr/assets/77852099/a561df51-4181-45f6-a192-0cbc72d9a912">

The building configurations as below
<img width="955" alt="截圖 2024-07-05 晚上8 12 42" src="https://github.com/gnss-sdr/gnss-sdr/assets/77852099/45ded9cc-f887-48a2-a9a8-1a9d78478b4c">

<img width="944" alt="截圖 2024-07-05 晚上8 14 08" src="https://github.com/gnss-sdr/gnss-sdr/assets/77852099/6253ab92-4190-4528-ae73-4dc707a3690d">

Am I compiling in a wrong way?

**Comment by jwmelto** [comment]
your first error is on `gr::sync_block` which suggests that the GNU Radio you installed is not M3 native. You might try building it from source as well, or check with the GNU Radio project.

**Comment by carlesfernandez** [comment]
I can't reproduce this error in your very same hardware. I could build the software in the same architecture and OS (M3, Sonoma 14) without issues. Please review your GNU Radio installation.
