### ISSUE TITLE
Questions about saved source data, baseband? sampling rate? datatype?

### ISSUE THREAD

**Issue by XueWei08** [gnss-sdr/gnss-sdr#788]
Hello, I am using USRP B200 and MacBook Pro 14, the antenna is Tallysman Triple Band GNSS Antenna 33-7972-07, want to use GNSS-SDR in real-time and also save source data for post-processing.

 I have some questions about the saved source data, 
1) I didn't find the explanation about the source data, whether it is baseband signal or not IF signal? is there a way to choose it?
2) the saved source signal is stored at datatype as "ishort" or "gr_complex" or other? is there a way to set it?
The description only says that set "dump" to be true to save it but does not mention its datatype.
<img width="661" alt="Screenshot 2024-08-05 at 3 38 29 PM" src="https://github.com/user-attachments/assets/6b190849-bd57-4e4a-9819-aa1cba633631">

3) the sampling rate for GPS L1 is 4M Hz?  or 2M Hz is enough?
The bandwidth of GPS L1 C/A is 2.046 MHz, so I thought we should use at least twice of it, which is about 4M Hz. But I tried 2M Hz and 4M Hz, both works, so I am a little confused.

Does anyone have ideas about it?
Thanks in advance!

**Comment by jmfriedt** [comment]
"whether it is baseband signal or not IF signal? is there a way to choose it?"

Depending on your SDR setting, the signal can be baseband or with IF and gnss-sdr can take care of the frequency transposition using a Frequency Xlating FIR Fillter (https://wiki.gnuradio.org/index.php/Frequency_Xlating_FIR_Filter). See for eg gnss-sdr_GPS_L1_rtlsdr_realtime.conf in the conf/ subdirectory for an example of setting the Xlating FIR Filter IF frequency and low pass

"the saved source signal is stored at datatype as "ishort" or "gr_complex" or other? is there a way to set it?"

This depends on your SDR source. If the data is preprocessed using for e.g. GNU Radio, then the output of the last GNU Radio block (e.g. ZMQ Publish) will define the file format. For UHD it will be complex float by default https://wiki.gnuradio.org/index.php/USRP_Source although the data type can be changed to save bandwidth

"the sampling rate for GPS L1 is 4M Hz? or 2M Hz is enough?"

1.023 MS/s is 2.046 MHz bandwidth which is the span of a *complex* IQ stream at 2 MS/s.
