### ISSUE TITLE
Hot start

### ISSUE THREAD

**Issue by Derso1** [gnss-sdr/gnss-sdr#817]
Hi every one

I started to use the hot start in the gnss sdr. In the normal way I get PVT after 47 seg more or less. When I am using hot start I can get the PVT solution in more or less 25 seg.

Anyway, My question is:

After how long time I need to change the rinex file that I use in the process of hot start?

TKS

**Comment by carlesfernandez** [comment]
You should change the RINEX file each time the ephemeris changes. In GPS L1, this is every two hours.
