### ISSUE TITLE
Tracking does not lock on signals captured by FMCOMMS3

### ISSUE THREAD

**Issue by pedromiguelcp** [gnss-sdr/gnss-sdr#821]
I'm using FMCOMMS3 to capture GPS signals. The signals are acquired. However, as soon as the tracking begins, the correlator values ​​drop. Can anyone help me understand what could be wrong with my configuration or if any filtering is needed on the captured data?

I appreciate any help you can provide.

The configuration used is below:

`[GNSS-SDR]
 
;######### GLOBAL OPTIONS ##################
;internal_fs_sps: Internal signal sampling frequency after the signal conditioning stage [samples per second].
GNSS-SDR.internal_fs_sps=12500000

 
;######### CONTROL_THREAD CONFIG ############
ControlThread.wait_for_flowgraph=false
 
;######### SIGNAL_SOURCE CONFIG ############
SignalSource.implementation=Fmcomms2_Signal_Source
SignalSource.device_address=192.168.1.102
SignalSource.sampling_frequency=12500000
SignalSource.freq=1575420000
SignalSource.bandwidth=2000000
SignalSource.rx1_enable=true
SignalSource.gain_mode_rx1=slow_attack

;######### SIGNAL_CONDITIONER CONFIG ############
SignalConditioner.implementation=Pass_Through
 
;######### INPUT_FILTER CONFIG ############
InputFilter.implementation=Pass_Through
InputFilter.input_item_type=gr_complex
InputFilter.output_item_type=gr_complex
 
;######### RESAMPLER CONFIG ############
Resampler.implementation=Direct_Resampler
Resampler.sample_freq_in=12500000;25000000
Resampler.sample_freq_out=12500000;25000000
Resampler.item_type=gr_complex
 
 
;######### CHANNELS GLOBAL CONFIG ############
Channels_1C.count=8
Channels.in_acquisition=1
Channel.signal=1C
 
 
;######### ACQUISITION GLOBAL CONFIG ############
Acquisition_1C.implementation=GPS_L1_CA_PCPS_Acquisition
Acquisition_1C.item_type=gr_complex
Acquisition_1C.coherent_integration_time_ms=1
Acquisition_1C.pfa=0.01
Acquisition_1C.doppler_max=10000
Acquisition_1C.doppler_step=250
Acquisition_1C.dump=false
Acquisition_1C.dump_filename=./data_out/acq/inverted_
 
;######### TRACKING GLOBAL CONFIG ############
Tracking_1C.implementation=GPS_L1_CA_DLL_PLL_Tracking
Tracking_1C.item_type=gr_complex
Tracking_1C.pll_bw_hz=40.0;
Tracking_1C.dll_bw_hz=4.0;
Tracking_1C.order=3;
Tracking_1C.early_late_space_chips=0.5
;Tracking_1C.fll_bw_hz=10
;Tracking_1C.enable_fll_pull_in=true;
Tracking_1C.dump=true;
Tracking_1C.dump_filename=./outputs_tmp/tracking_ch_
 
 
;######### TELEMETRY DECODER GPS CONFIG ############
TelemetryDecoder_1C.implementation=GPS_L1_CA_Telemetry_Decoder
TelemetryDecoder_1C.dump=false
 
 
;######### OBSERVABLES CONFIG ############
Observables.implementation=Hybrid_Observables
Observables.dump=false
Observables.dump_filename=./data_out/observables.dat
 
 
;######### PVT CONFIG ############
PVT.implementation=RTKLIB_PVT
PVT.positioning_mode=PPP_Kinematic  ; options: Single, Static, Kinematic, PPP_Static, PPP_Kinematic
PVT.iono_model=Broadcast ; options: OFF, Broadcast, SBAS, Iono-Free-LC, Estimate_STEC, IONEX
PVT.trop_model=Saastamoinen ; options: OFF, Saastamoinen, SBAS, Estimate_ZTD, Estimate_ZTD_Grad
PVT.output_rate_ms=100
PVT.display_rate_ms=500
PVT.dump_filename=./
PVT.nmea_dump_filename=./gnss_sdr_pvt.nmea;
PVT.nmea_output_file_enabled=false
PVT.nmea_rate_ms=1000
PVT.dump=false
PVT.enable_monitor=false
PVT.flag_nmea_tty_port=false
PVT.nmea_dump_devname=/dev/pts/4
PVT.flag_rtcm_server=false
PVT.flag_rtcm_tty_port=false
PVT.rtcm_dump_devname=/dev/pts/1`

**Comment by carlesfernandez** [comment]
The FMCOMMS3 requires a replacement of the TCXO for GNSS signal processing, or a feed from an external clock with proper stability.
