### ISSUE TITLE
Up grade of Rinex file

### ISSUE THREAD

**Issue by Derso1** [gnss-sdr/gnss-sdr#823]
Hi
I am using rinex2assist and the hot start is working well, but I would like to know if I need to change the Rinex navegation file hourly or weekly is ok?

**Comment by carlesfernandez** [comment]
The GPS ephemeris has a validation of two hours.

**Comment by jwmelto** [comment]
I thought it was valid for 4 hours but updated every 2 hours. Not a big deal either way.

**Comment by Derso1** [comment]
Tks a lot @carlesfernandez and @jwmelto 
I will test your sugesttion in my simulator.
